// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Close.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Close.OpenApiClient.Phone_number.Request.Internal
{
    /// <summary>
    /// Builds and executes requests for operations under \phone_number\request\internal
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class InternalRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Close.OpenApiClient.Phone_number.Request.Internal.InternalRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public InternalRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/phone_number/request/internal", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Close.OpenApiClient.Phone_number.Request.Internal.InternalRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public InternalRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/phone_number/request/internal", rawUrl)
        {
        }
        /// <summary>
        /// &quot;Renting a phone number incurs a cost. You need the \&quot;Manage Group Phone Numbers\&quot; permission to rent group numbers.If a number was rented, a 201 response is returned with the new number. If no number was rented (4xx response code), the response contains a `status` field which may contain one of the values below. New statuses may be added in the future.* `has-voice-only`: This country/prefix combination only has non-SMS-capable  numbers. You can attempt renting the number by passing `with_sms` as `false`.* `needs-more-info`: More information (such as proof of address) is needed to  rent this number. This number can only be rented by contacting Close support.* `billing-error`: An error related to billing has occurred. For example, the  telephony budget has been reached, or there are not enough funds and recharging failed.* `error`: An error has occurred while renting this number. A human-readable  message is returned in the `error` field.&quot;
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Close.OpenApiClient.Models.DefaultResponseResponseJson133"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Close.OpenApiClient.Models.DefaultResponseResponseJson133?> PostAsync(global::Soenneker.Close.OpenApiClient.Models.CreatePhoneNumberRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Close.OpenApiClient.Models.DefaultResponseResponseJson133> PostAsync(global::Soenneker.Close.OpenApiClient.Models.CreatePhoneNumberRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Close.OpenApiClient.Models.DefaultResponseResponseJson133>(requestInfo, global::Soenneker.Close.OpenApiClient.Models.DefaultResponseResponseJson133.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// &quot;Renting a phone number incurs a cost. You need the \&quot;Manage Group Phone Numbers\&quot; permission to rent group numbers.If a number was rented, a 201 response is returned with the new number. If no number was rented (4xx response code), the response contains a `status` field which may contain one of the values below. New statuses may be added in the future.* `has-voice-only`: This country/prefix combination only has non-SMS-capable  numbers. You can attempt renting the number by passing `with_sms` as `false`.* `needs-more-info`: More information (such as proof of address) is needed to  rent this number. This number can only be rented by contacting Close support.* `billing-error`: An error related to billing has occurred. For example, the  telephony budget has been reached, or there are not enough funds and recharging failed.* `error`: An error has occurred while renting this number. A human-readable  message is returned in the `error` field.&quot;
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.Close.OpenApiClient.Models.CreatePhoneNumberRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.Close.OpenApiClient.Models.CreatePhoneNumberRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Close.OpenApiClient.Phone_number.Request.Internal.InternalRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Close.OpenApiClient.Phone_number.Request.Internal.InternalRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Close.OpenApiClient.Phone_number.Request.Internal.InternalRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
