// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Close.OpenApiClient.Activity.Meeting.Item.Integration;
using Soenneker.Close.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Close.OpenApiClient.Activity.Meeting.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \activity\meeting\{id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MeetingItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The integration property</summary>
        public global::Soenneker.Close.OpenApiClient.Activity.Meeting.Item.Integration.IntegrationRequestBuilder Integration
        {
            get => new global::Soenneker.Close.OpenApiClient.Activity.Meeting.Item.Integration.IntegrationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Close.OpenApiClient.Activity.Meeting.Item.MeetingItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MeetingItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/activity/meeting/{id}{?_fields*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Close.OpenApiClient.Activity.Meeting.Item.MeetingItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MeetingItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/activity/meeting/{id}{?_fields*}", rawUrl)
        {
        }
        /// <summary>
        /// Delete a Meeting activity
        /// </summary>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToDeleteRequestInformation(requestConfiguration);
            await RequestAdapter.SendNoContentAsync(requestInfo, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// &quot;Meeting transcripts can be accessed using this API but are not loaded by default. To load transcripts, use the `_fields` parameter with `transcripts` value.The `transcripts` field is an array of objects for each Close Notetaker bot that joined the meeting. Typically, there will be only one transcript. Transcripts are ordered by the time bots joined the meeting.Example transcripts in response:```json{ \&quot;transcripts\&quot;: [ { \&quot;utterances\&quot;: [ { \&quot;speaker_label\&quot;: \&quot;John Lead\&quot;, \&quot;speaker_side\&quot;: \&quot;contact\&quot;, \&quot;start\&quot;: 0.1, \&quot;end\&quot;: 1.2, \&quot;text\&quot;: \&quot;Hey, what&apos;s up? How is it going?\&quot; }, { \&quot;speaker_label\&quot;: \&quot;Jane User\&quot;, \&quot;speaker_side\&quot;: \&quot;close-user\&quot;, \&quot;start\&quot;: 1.3, \&quot;end\&quot;: 2.4, \&quot;text\&quot;: \&quot;Hey John, I&apos;m doing great. How about you?\&quot; } ], \&quot;summary_text\&quot;: \&quot;Summary text\&quot;, \&quot;summary_html\&quot;: \&quot;&lt;p&gt;Summary text&lt;/p&gt;\&quot; } ] }```&quot;
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Close.OpenApiClient.Models.DefaultResponseResponseJson17"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Close.OpenApiClient.Models.DefaultResponseResponseJson17?> GetAsync(Action<RequestConfiguration<global::Soenneker.Close.OpenApiClient.Activity.Meeting.Item.MeetingItemRequestBuilder.MeetingItemRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Close.OpenApiClient.Models.DefaultResponseResponseJson17> GetAsync(Action<RequestConfiguration<global::Soenneker.Close.OpenApiClient.Activity.Meeting.Item.MeetingItemRequestBuilder.MeetingItemRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Close.OpenApiClient.Models.DefaultResponseResponseJson17>(requestInfo, global::Soenneker.Close.OpenApiClient.Models.DefaultResponseResponseJson17.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Most commonly this can be used to update a meetings&apos;s `user_note_html` or `outcome_id`.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Close.OpenApiClient.Models.DefaultResponseResponseJson18"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Close.OpenApiClient.Models.DefaultResponseResponseJson18?> PutAsync(global::Soenneker.Close.OpenApiClient.Models.ActivitiesMeetingsUpdateRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Close.OpenApiClient.Models.DefaultResponseResponseJson18> PutAsync(global::Soenneker.Close.OpenApiClient.Models.ActivitiesMeetingsUpdateRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPutRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Close.OpenApiClient.Models.DefaultResponseResponseJson18>(requestInfo, global::Soenneker.Close.OpenApiClient.Models.DefaultResponseResponseJson18.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Delete a Meeting activity
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.DELETE, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// &quot;Meeting transcripts can be accessed using this API but are not loaded by default. To load transcripts, use the `_fields` parameter with `transcripts` value.The `transcripts` field is an array of objects for each Close Notetaker bot that joined the meeting. Typically, there will be only one transcript. Transcripts are ordered by the time bots joined the meeting.Example transcripts in response:```json{ \&quot;transcripts\&quot;: [ { \&quot;utterances\&quot;: [ { \&quot;speaker_label\&quot;: \&quot;John Lead\&quot;, \&quot;speaker_side\&quot;: \&quot;contact\&quot;, \&quot;start\&quot;: 0.1, \&quot;end\&quot;: 1.2, \&quot;text\&quot;: \&quot;Hey, what&apos;s up? How is it going?\&quot; }, { \&quot;speaker_label\&quot;: \&quot;Jane User\&quot;, \&quot;speaker_side\&quot;: \&quot;close-user\&quot;, \&quot;start\&quot;: 1.3, \&quot;end\&quot;: 2.4, \&quot;text\&quot;: \&quot;Hey John, I&apos;m doing great. How about you?\&quot; } ], \&quot;summary_text\&quot;: \&quot;Summary text\&quot;, \&quot;summary_html\&quot;: \&quot;&lt;p&gt;Summary text&lt;/p&gt;\&quot; } ] }```&quot;
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Close.OpenApiClient.Activity.Meeting.Item.MeetingItemRequestBuilder.MeetingItemRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Close.OpenApiClient.Activity.Meeting.Item.MeetingItemRequestBuilder.MeetingItemRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Most commonly this can be used to update a meetings&apos;s `user_note_html` or `outcome_id`.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPutRequestInformation(global::Soenneker.Close.OpenApiClient.Models.ActivitiesMeetingsUpdateRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPutRequestInformation(global::Soenneker.Close.OpenApiClient.Models.ActivitiesMeetingsUpdateRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PUT, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Close.OpenApiClient.Activity.Meeting.Item.MeetingItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Close.OpenApiClient.Activity.Meeting.Item.MeetingItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Close.OpenApiClient.Activity.Meeting.Item.MeetingItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// &quot;Meeting transcripts can be accessed using this API but are not loaded by default. To load transcripts, use the `_fields` parameter with `transcripts` value.The `transcripts` field is an array of objects for each Close Notetaker bot that joined the meeting. Typically, there will be only one transcript. Transcripts are ordered by the time bots joined the meeting.Example transcripts in response:```json{ \&quot;transcripts\&quot;: [ { \&quot;utterances\&quot;: [ { \&quot;speaker_label\&quot;: \&quot;John Lead\&quot;, \&quot;speaker_side\&quot;: \&quot;contact\&quot;, \&quot;start\&quot;: 0.1, \&quot;end\&quot;: 1.2, \&quot;text\&quot;: \&quot;Hey, what&apos;s up? How is it going?\&quot; }, { \&quot;speaker_label\&quot;: \&quot;Jane User\&quot;, \&quot;speaker_side\&quot;: \&quot;close-user\&quot;, \&quot;start\&quot;: 1.3, \&quot;end\&quot;: 2.4, \&quot;text\&quot;: \&quot;Hey John, I&apos;m doing great. How about you?\&quot; } ], \&quot;summary_text\&quot;: \&quot;Summary text\&quot;, \&quot;summary_html\&quot;: \&quot;&lt;p&gt;Summary text&lt;/p&gt;\&quot; } ] }```&quot;
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class MeetingItemRequestBuilderGetQueryParameters 
        {
            /// <summary>Comma-separated list of fields to include in the response.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("_fields")]
            public string? Fields { get; set; }
#nullable restore
#else
            [QueryParameter("_fields")]
            public string Fields { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
