// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Close.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Close.OpenApiClient.Email_template.Item.Render
{
    /// <summary>
    /// Builds and executes requests for operations under \email_template\{id}\render
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class RenderRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Close.OpenApiClient.Email_template.Item.Render.RenderRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RenderRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/email_template/{id}/render{?bulk_object_type*,contact_id*,contact_preference*,email_account_id*,entry*,lead_id*,limit*,mode*,query*,results_limit*,s_query*,sender*,sort*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Close.OpenApiClient.Email_template.Item.Render.RenderRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RenderRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/email_template/{id}/render{?bulk_object_type*,contact_id*,contact_preference*,email_account_id*,entry*,lead_id*,limit*,mode*,query*,results_limit*,s_query*,sender*,sort*}", rawUrl)
        {
        }
        /// <summary>
        /// Render an email template for the given lead/contact using the current user context.Accepts two forms of usage:- Single lead/contact:  - `lead_id` and `contact_id` is supplied (both required)- Preview results from a search query  - `query` (required) contains a search query  - `entry` (optional, ranges from 0 to 99) specifies the index of the lead/contact that should be rendered.  - `mode` (optional), which can have a value of:     - `lead` (default), the first contact of the lead with the index given by `entry` will be rendered (excluding leads that have no email addresses).     - `contact`, then `entry` refers to the index of the contact (excluding contacts that have no emails). Will return an empty dict if there are no more entries.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Close.OpenApiClient.Models.DefaultResponseResponseJson104"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Close.OpenApiClient.Models.DefaultResponseResponseJson104?> GetAsync(Action<RequestConfiguration<global::Soenneker.Close.OpenApiClient.Email_template.Item.Render.RenderRequestBuilder.RenderRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Close.OpenApiClient.Models.DefaultResponseResponseJson104> GetAsync(Action<RequestConfiguration<global::Soenneker.Close.OpenApiClient.Email_template.Item.Render.RenderRequestBuilder.RenderRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Close.OpenApiClient.Models.DefaultResponseResponseJson104>(requestInfo, global::Soenneker.Close.OpenApiClient.Models.DefaultResponseResponseJson104.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Render an email template for the given lead/contact using the current user context.Accepts two forms of usage:- Single lead/contact:  - `lead_id` and `contact_id` is supplied (both required)- Preview results from a search query  - `query` (required) contains a search query  - `entry` (optional, ranges from 0 to 99) specifies the index of the lead/contact that should be rendered.  - `mode` (optional), which can have a value of:     - `lead` (default), the first contact of the lead with the index given by `entry` will be rendered (excluding leads that have no email addresses).     - `contact`, then `entry` refers to the index of the contact (excluding contacts that have no emails). Will return an empty dict if there are no more entries.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Close.OpenApiClient.Email_template.Item.Render.RenderRequestBuilder.RenderRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Close.OpenApiClient.Email_template.Item.Render.RenderRequestBuilder.RenderRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Close.OpenApiClient.Email_template.Item.Render.RenderRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Close.OpenApiClient.Email_template.Item.Render.RenderRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Close.OpenApiClient.Email_template.Item.Render.RenderRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Render an email template for the given lead/contact using the current user context.Accepts two forms of usage:- Single lead/contact:  - `lead_id` and `contact_id` is supplied (both required)- Preview results from a search query  - `query` (required) contains a search query  - `entry` (optional, ranges from 0 to 99) specifies the index of the lead/contact that should be rendered.  - `mode` (optional), which can have a value of:     - `lead` (default), the first contact of the lead with the index given by `entry` will be rendered (excluding leads that have no email addresses).     - `contact`, then `entry` refers to the index of the contact (excluding contacts that have no emails). Will return an empty dict if there are no more entries.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class RenderRequestBuilderGetQueryParameters 
        {
            [QueryParameter("bulk_object_type")]
            public global::Soenneker.Close.OpenApiClient.Models.EmailTemplatesRenderBulkObjectTypeParameter? BulkObjectType { get; set; }
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("contact_id")]
            public string? ContactId { get; set; }
#nullable restore
#else
            [QueryParameter("contact_id")]
            public string ContactId { get; set; }
#endif
            [QueryParameter("contact_preference")]
            public global::Soenneker.Close.OpenApiClient.Models.EmailTemplatesRenderContactPreferenceParameter? ContactPreference { get; set; }
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("email_account_id")]
            public string? EmailAccountId { get; set; }
#nullable restore
#else
            [QueryParameter("email_account_id")]
            public string EmailAccountId { get; set; }
#endif
            [QueryParameter("entry")]
            public int? Entry { get; set; }
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("lead_id")]
            public string? LeadId { get; set; }
#nullable restore
#else
            [QueryParameter("lead_id")]
            public string LeadId { get; set; }
#endif
            [QueryParameter("limit")]
            public int? Limit { get; set; }
            [QueryParameter("mode")]
            public global::Soenneker.Close.OpenApiClient.Models.EmailTemplatesRenderModeParameter? Mode { get; set; }
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("query")]
            public string? Query { get; set; }
#nullable restore
#else
            [QueryParameter("query")]
            public string Query { get; set; }
#endif
            [QueryParameter("results_limit")]
            public int? ResultsLimit { get; set; }
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("sender")]
            public string? Sender { get; set; }
#nullable restore
#else
            [QueryParameter("sender")]
            public string Sender { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("sort")]
            public string[]? Sort { get; set; }
#nullable restore
#else
            [QueryParameter("sort")]
            public string[] Sort { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("s_query")]
            public string? SQuery { get; set; }
#nullable restore
#else
            [QueryParameter("s_query")]
            public string SQuery { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
