// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Close.OpenApiClient.Models;
using Soenneker.Close.OpenApiClient.Phone_number.Item;
using Soenneker.Close.OpenApiClient.Phone_number.Request;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Close.OpenApiClient.Phone_number
{
    /// <summary>
    /// Builds and executes requests for operations under \phone_number
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Phone_numberRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The request property</summary>
        public global::Soenneker.Close.OpenApiClient.Phone_number.Request.RequestRequestBuilder Request
        {
            get => new global::Soenneker.Close.OpenApiClient.Phone_number.Request.RequestRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Soenneker.Close.OpenApiClient.phone_number.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Soenneker.Close.OpenApiClient.Phone_number.Item.Phone_numberItemRequestBuilder"/></returns>
        public global::Soenneker.Close.OpenApiClient.Phone_number.Item.Phone_numberItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id", position);
                return new global::Soenneker.Close.OpenApiClient.Phone_number.Item.Phone_numberItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Close.OpenApiClient.Phone_number.Phone_numberRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Phone_numberRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/phone_number{?_fields*,_limit*,_skip*,is_group_number*,number*,participant_user_id*,user_id*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Close.OpenApiClient.Phone_number.Phone_numberRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Phone_numberRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/phone_number{?_fields*,_limit*,_skip*,is_group_number*,number*,participant_user_id*,user_id*}", rawUrl)
        {
        }
        /// <summary>
        /// List or search for phone numbers
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Close.OpenApiClient.Models.PhoneNumbersList200Response"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Close.OpenApiClient.Models.PhoneNumbersList200Response?> GetAsync(Action<RequestConfiguration<global::Soenneker.Close.OpenApiClient.Phone_number.Phone_numberRequestBuilder.Phone_numberRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Close.OpenApiClient.Models.PhoneNumbersList200Response> GetAsync(Action<RequestConfiguration<global::Soenneker.Close.OpenApiClient.Phone_number.Phone_numberRequestBuilder.Phone_numberRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Close.OpenApiClient.Models.PhoneNumbersList200Response>(requestInfo, global::Soenneker.Close.OpenApiClient.Models.PhoneNumbersList200Response.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// List or search for phone numbers
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Close.OpenApiClient.Phone_number.Phone_numberRequestBuilder.Phone_numberRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Close.OpenApiClient.Phone_number.Phone_numberRequestBuilder.Phone_numberRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Close.OpenApiClient.Phone_number.Phone_numberRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Close.OpenApiClient.Phone_number.Phone_numberRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Close.OpenApiClient.Phone_number.Phone_numberRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// List or search for phone numbers
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Phone_numberRequestBuilderGetQueryParameters 
        {
            /// <summary>Comma-separated list of fields to include in the response.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("_fields")]
            public string? Fields { get; set; }
#nullable restore
#else
            [QueryParameter("_fields")]
            public string Fields { get; set; }
#endif
            /// <summary>Deprecated. Use `participant_user_id` instead. The distinction between personal and group numbers is being removed, and `is_group_number` will be removed in a future update.</summary>
            [Obsolete("")]
            [QueryParameter("is_group_number")]
            public bool? IsGroupNumber { get; set; }
            /// <summary>Number of results to return.</summary>
            [QueryParameter("_limit")]
            public int? Limit { get; set; }
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("number")]
            public string? Number { get; set; }
#nullable restore
#else
            [QueryParameter("number")]
            public string Number { get; set; }
#endif
            /// <summary>Return numbers the given user participates in, including both personal and group numbers they belong to.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("participant_user_id")]
            public string? ParticipantUserId { get; set; }
#nullable restore
#else
            [QueryParameter("participant_user_id")]
            public string ParticipantUserId { get; set; }
#endif
            /// <summary>Number of results to skip before returning, for pagination.</summary>
            [QueryParameter("_skip")]
            public int? Skip { get; set; }
            /// <summary>Deprecated. Use `participant_user_id` instead. The distinction between personal and group numbers is being removed, and `user_id` will be removed in a future update.</summary>
            [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("user_id")]
            public string? UserId { get; set; }
#nullable restore
#else
            [QueryParameter("user_id")]
            public string UserId { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
