// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Close.OpenApiClient.Custom_field.Shared.Item.Association.Item;
using Soenneker.Close.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Close.OpenApiClient.Custom_field.Shared.Item.Association
{
    /// <summary>
    /// Builds and executes requests for operations under \custom_field\shared\{-id}\association
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AssociationRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Close.OpenApiClient.custom_field.shared.item.association.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Soenneker.Close.OpenApiClient.Custom_field.Shared.Item.Association.Item.WithObjectTypeItemRequestBuilder"/></returns>
        public global::Soenneker.Close.OpenApiClient.Custom_field.Shared.Item.Association.Item.WithObjectTypeItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("objectType", position);
                return new global::Soenneker.Close.OpenApiClient.Custom_field.Shared.Item.Association.Item.WithObjectTypeItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Close.OpenApiClient.Custom_field.Shared.Item.Association.AssociationRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AssociationRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/custom_field/shared/{%2Did}/association", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Close.OpenApiClient.Custom_field.Shared.Item.Association.AssociationRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AssociationRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/custom_field/shared/{%2Did}/association", rawUrl)
        {
        }
        /// <summary>
        /// &quot;Associates a Shared Custom Field with an object type such as Lead, Contact, or Custom Activity Type. Once associated, the Shared Custom Field can be set on objects of that type.This endpoint accepts the following attributes:- `object_type` – can be one of: `lead`, `contact`, `opportunity`, `custom_activity_type`,  `custom_object_type`.- `custom_activity_type_id` – ID of the Custom Activity Type that you want to  associate this Shared Field with. Only relevant if you chose the `object_type` of `custom_activity_type`.- `custom_object_type_id` – ID of the Custom Object Type that you want to  associate this Shared Field with. Only relevant if you chose the `object_type` of `custom_object_type`.- `editable_with_roles` – list of [Roles](https://developer.close.com/api/resources/roles) that can edit the values of  this Field on the given object. Note that this is a per-association setting, meaning that editing of the Shared Custom Field can be restricted on one object and not restricted on another.- `required` – whether a value *must* be provided for this Field on the given  object. Only relevant if you chose the `object_type` of `custom_activity_type` or `custom_object_type`. Note that this is a per-association setting, meaning that this Shared Custom Field can be required on one object and not required on another.&quot;
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Close.OpenApiClient.Models.DefaultResponseResponseJson81"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Close.OpenApiClient.Models.DefaultResponseResponseJson81?> PostAsync(global::Soenneker.Close.OpenApiClient.Models.CustomFieldsSharedCreateAssociationRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Close.OpenApiClient.Models.DefaultResponseResponseJson81> PostAsync(global::Soenneker.Close.OpenApiClient.Models.CustomFieldsSharedCreateAssociationRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Close.OpenApiClient.Models.DefaultResponseResponseJson81>(requestInfo, global::Soenneker.Close.OpenApiClient.Models.DefaultResponseResponseJson81.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// &quot;Associates a Shared Custom Field with an object type such as Lead, Contact, or Custom Activity Type. Once associated, the Shared Custom Field can be set on objects of that type.This endpoint accepts the following attributes:- `object_type` – can be one of: `lead`, `contact`, `opportunity`, `custom_activity_type`,  `custom_object_type`.- `custom_activity_type_id` – ID of the Custom Activity Type that you want to  associate this Shared Field with. Only relevant if you chose the `object_type` of `custom_activity_type`.- `custom_object_type_id` – ID of the Custom Object Type that you want to  associate this Shared Field with. Only relevant if you chose the `object_type` of `custom_object_type`.- `editable_with_roles` – list of [Roles](https://developer.close.com/api/resources/roles) that can edit the values of  this Field on the given object. Note that this is a per-association setting, meaning that editing of the Shared Custom Field can be restricted on one object and not restricted on another.- `required` – whether a value *must* be provided for this Field on the given  object. Only relevant if you chose the `object_type` of `custom_activity_type` or `custom_object_type`. Note that this is a per-association setting, meaning that this Shared Custom Field can be required on one object and not required on another.&quot;
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.Close.OpenApiClient.Models.CustomFieldsSharedCreateAssociationRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.Close.OpenApiClient.Models.CustomFieldsSharedCreateAssociationRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Close.OpenApiClient.Custom_field.Shared.Item.Association.AssociationRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Close.OpenApiClient.Custom_field.Shared.Item.Association.AssociationRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Close.OpenApiClient.Custom_field.Shared.Item.Association.AssociationRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
