// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Close.OpenApiClient.Models
{
    /// <summary>Whether this member&apos;s calls are automatically recorded. Starts as `unset` and can be set to `enabled` or `disabled`.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum AutoRecordCalls
    {
        [EnumMember(Value = "enabled")]
        #pragma warning disable CS1591
        Enabled,
        #pragma warning restore CS1591
        [EnumMember(Value = "disabled")]
        #pragma warning disable CS1591
        Disabled,
        #pragma warning restore CS1591
        [EnumMember(Value = "unset")]
        #pragma warning disable CS1591
        Unset,
        #pragma warning restore CS1591
    }
}
