// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Close.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class BasicSubscriptionInfoForContact : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The contact_email property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ContactEmail { get; set; }
#nullable restore
#else
        public string ContactEmail { get; set; }
#endif
        /// <summary>The date_created property</summary>
        public DateTimeOffset? DateCreated { get; set; }
        /// <summary>The initial_email_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? InitialEmailId { get; set; }
#nullable restore
#else
        public string InitialEmailId { get; set; }
#endif
        /// <summary>The sequence_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SequenceId { get; set; }
#nullable restore
#else
        public string SequenceId { get; set; }
#endif
        /// <summary>The sequence_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SequenceName { get; set; }
#nullable restore
#else
        public string SequenceName { get; set; }
#endif
        /// <summary>The sequence_status property</summary>
        public global::Soenneker.Close.OpenApiClient.Models.WorkflowStatus? SequenceStatus { get; set; }
        /// <summary>The start_date property</summary>
        public DateTimeOffset? StartDate { get; set; }
        /// <summary>The subscription_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SubscriptionId { get; set; }
#nullable restore
#else
        public string SubscriptionId { get; set; }
#endif
        /// <summary>The subscription_status property</summary>
        public global::Soenneker.Close.OpenApiClient.Models.WorkflowRunStatus? SubscriptionStatus { get; set; }
        /// <summary>The subscription_status_reason property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Close.OpenApiClient.Models.StatusReasonWrapper? SubscriptionStatusReason { get; set; }
#nullable restore
#else
        public global::Soenneker.Close.OpenApiClient.Models.StatusReasonWrapper SubscriptionStatusReason { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Close.OpenApiClient.Models.BasicSubscriptionInfoForContact"/> and sets the default values.
        /// </summary>
        public BasicSubscriptionInfoForContact()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Close.OpenApiClient.Models.BasicSubscriptionInfoForContact"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Close.OpenApiClient.Models.BasicSubscriptionInfoForContact CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Close.OpenApiClient.Models.BasicSubscriptionInfoForContact();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "contact_email", n => { ContactEmail = n.GetStringValue(); } },
                { "date_created", n => { DateCreated = n.GetDateTimeOffsetValue(); } },
                { "initial_email_id", n => { InitialEmailId = n.GetStringValue(); } },
                { "sequence_id", n => { SequenceId = n.GetStringValue(); } },
                { "sequence_name", n => { SequenceName = n.GetStringValue(); } },
                { "sequence_status", n => { SequenceStatus = n.GetEnumValue<global::Soenneker.Close.OpenApiClient.Models.WorkflowStatus>(); } },
                { "start_date", n => { StartDate = n.GetDateTimeOffsetValue(); } },
                { "subscription_id", n => { SubscriptionId = n.GetStringValue(); } },
                { "subscription_status", n => { SubscriptionStatus = n.GetEnumValue<global::Soenneker.Close.OpenApiClient.Models.WorkflowRunStatus>(); } },
                { "subscription_status_reason", n => { SubscriptionStatusReason = n.GetObjectValue<global::Soenneker.Close.OpenApiClient.Models.StatusReasonWrapper>(global::Soenneker.Close.OpenApiClient.Models.StatusReasonWrapper.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("contact_email", ContactEmail);
            writer.WriteDateTimeOffsetValue("date_created", DateCreated);
            writer.WriteStringValue("initial_email_id", InitialEmailId);
            writer.WriteStringValue("sequence_id", SequenceId);
            writer.WriteStringValue("sequence_name", SequenceName);
            writer.WriteEnumValue<global::Soenneker.Close.OpenApiClient.Models.WorkflowStatus>("sequence_status", SequenceStatus);
            writer.WriteDateTimeOffsetValue("start_date", StartDate);
            writer.WriteStringValue("subscription_id", SubscriptionId);
            writer.WriteEnumValue<global::Soenneker.Close.OpenApiClient.Models.WorkflowRunStatus>("subscription_status", SubscriptionStatus);
            writer.WriteObjectValue<global::Soenneker.Close.OpenApiClient.Models.StatusReasonWrapper>("subscription_status_reason", SubscriptionStatusReason);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
