// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Close.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum BulkEditActionType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "set_custom_field")]
        #pragma warning disable CS1591
        SetCustomField,
        #pragma warning restore CS1591
        [EnumMember(Value = "clear_custom_field")]
        #pragma warning disable CS1591
        ClearCustomField,
        #pragma warning restore CS1591
        [EnumMember(Value = "set_lead_status")]
        #pragma warning disable CS1591
        SetLeadStatus,
        #pragma warning restore CS1591
        [EnumMember(Value = "set_contact_custom_field")]
        #pragma warning disable CS1591
        SetContactCustomField,
        #pragma warning restore CS1591
        [EnumMember(Value = "clear_contact_custom_field")]
        #pragma warning disable CS1591
        ClearContactCustomField,
        #pragma warning restore CS1591
        [EnumMember(Value = "set_activity_custom_field")]
        #pragma warning disable CS1591
        SetActivityCustomField,
        #pragma warning restore CS1591
        [EnumMember(Value = "clear_activity_custom_field")]
        #pragma warning disable CS1591
        ClearActivityCustomField,
        #pragma warning restore CS1591
        [EnumMember(Value = "set_global_custom_field")]
        #pragma warning disable CS1591
        SetGlobalCustomField,
        #pragma warning restore CS1591
        [EnumMember(Value = "clear_global_custom_field")]
        #pragma warning disable CS1591
        ClearGlobalCustomField,
        #pragma warning restore CS1591
        [EnumMember(Value = "set_opportunity_custom_field")]
        #pragma warning disable CS1591
        SetOpportunityCustomField,
        #pragma warning restore CS1591
        [EnumMember(Value = "clear_opportunity_custom_field")]
        #pragma warning disable CS1591
        ClearOpportunityCustomField,
        #pragma warning restore CS1591
        [EnumMember(Value = "set_custom_object_custom_field")]
        #pragma warning disable CS1591
        SetCustomObjectCustomField,
        #pragma warning restore CS1591
        [EnumMember(Value = "clear_custom_object_custom_field")]
        #pragma warning disable CS1591
        ClearCustomObjectCustomField,
        #pragma warning restore CS1591
    }
}
