// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Close.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CreateContact : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The created_by property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedBy { get; set; }
#nullable restore
#else
        public string CreatedBy { get; set; }
#endif
        /// <summary>The date_created property</summary>
        public DateTimeOffset? DateCreated { get; set; }
        /// <summary>The emails property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Close.OpenApiClient.Models.CreateContactEmailsItem>? Emails { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Close.OpenApiClient.Models.CreateContactEmailsItem> Emails { get; set; }
#endif
        /// <summary>The lead_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LeadId { get; set; }
#nullable restore
#else
        public string LeadId { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The phones property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Close.OpenApiClient.Models.CreateContactPhonesItem>? Phones { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Close.OpenApiClient.Models.CreateContactPhonesItem> Phones { get; set; }
#endif
        /// <summary>IANA timezone identifier</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Timezone { get; set; }
#nullable restore
#else
        public string Timezone { get; set; }
#endif
        /// <summary>The title property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>The urls property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Close.OpenApiClient.Models.CreateContactUrlsItem>? Urls { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Close.OpenApiClient.Models.CreateContactUrlsItem> Urls { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Close.OpenApiClient.Models.CreateContact"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Close.OpenApiClient.Models.CreateContact CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Close.OpenApiClient.Models.CreateContact();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "created_by", n => { CreatedBy = n.GetStringValue(); } },
                { "date_created", n => { DateCreated = n.GetDateTimeOffsetValue(); } },
                { "emails", n => { Emails = n.GetCollectionOfObjectValues<global::Soenneker.Close.OpenApiClient.Models.CreateContactEmailsItem>(global::Soenneker.Close.OpenApiClient.Models.CreateContactEmailsItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "lead_id", n => { LeadId = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "phones", n => { Phones = n.GetCollectionOfObjectValues<global::Soenneker.Close.OpenApiClient.Models.CreateContactPhonesItem>(global::Soenneker.Close.OpenApiClient.Models.CreateContactPhonesItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "timezone", n => { Timezone = n.GetStringValue(); } },
                { "title", n => { Title = n.GetStringValue(); } },
                { "urls", n => { Urls = n.GetCollectionOfObjectValues<global::Soenneker.Close.OpenApiClient.Models.CreateContactUrlsItem>(global::Soenneker.Close.OpenApiClient.Models.CreateContactUrlsItem.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("created_by", CreatedBy);
            writer.WriteDateTimeOffsetValue("date_created", DateCreated);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Close.OpenApiClient.Models.CreateContactEmailsItem>("emails", Emails);
            writer.WriteStringValue("lead_id", LeadId);
            writer.WriteStringValue("name", Name);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Close.OpenApiClient.Models.CreateContactPhonesItem>("phones", Phones);
            writer.WriteStringValue("timezone", Timezone);
            writer.WriteStringValue("title", Title);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Close.OpenApiClient.Models.CreateContactUrlsItem>("urls", Urls);
        }
    }
}
#pragma warning restore CS0618
