// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Close.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CustomObjectsCreateRequest : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The customCf_cSh3fWT3rEJ1BFSezme2YAG6bPrZV5wUWKKrW4iN19g property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CustomCfCSh3fWT3rEJ1BFSezme2YAG6bPrZV5wUWKKrW4iN19g { get; set; }
#nullable restore
#else
        public string CustomCfCSh3fWT3rEJ1BFSezme2YAG6bPrZV5wUWKKrW4iN19g { get; set; }
#endif
        /// <summary>The customCf_jnxTQDKnSxCEBtD5dvZdNgTzC3CqeyWUyU349PBA9Wf property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CustomCfJnxTQDKnSxCEBtD5dvZdNgTzC3CqeyWUyU349PBA9Wf { get; set; }
#nullable restore
#else
        public string CustomCfJnxTQDKnSxCEBtD5dvZdNgTzC3CqeyWUyU349PBA9Wf { get; set; }
#endif
        /// <summary>The customCf_UpyNBvr6Rw8UBHh7zRboL3PYhbOVJl3XvwgPm3jg64S property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? CustomCfUpyNBvr6Rw8UBHh7zRboL3PYhbOVJl3XvwgPm3jg64S { get; set; }
#nullable restore
#else
        public List<string> CustomCfUpyNBvr6Rw8UBHh7zRboL3PYhbOVJl3XvwgPm3jg64S { get; set; }
#endif
        /// <summary>The custom_object_type_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CustomObjectTypeId { get; set; }
#nullable restore
#else
        public string CustomObjectTypeId { get; set; }
#endif
        /// <summary>The lead_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LeadId { get; set; }
#nullable restore
#else
        public string LeadId { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Close.OpenApiClient.Models.CustomObjectsCreateRequest"/> and sets the default values.
        /// </summary>
        public CustomObjectsCreateRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Close.OpenApiClient.Models.CustomObjectsCreateRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Close.OpenApiClient.Models.CustomObjectsCreateRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Close.OpenApiClient.Models.CustomObjectsCreateRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "custom.cf_cSh3fWT3rEJ1BFSezme2YAG6bPrZV5wUWKKrW4iN19g", n => { CustomCfCSh3fWT3rEJ1BFSezme2YAG6bPrZV5wUWKKrW4iN19g = n.GetStringValue(); } },
                { "custom.cf_jnxTQDKnSxCEBtD5dvZdNgTzC3CqeyWUyU349PBA9Wf", n => { CustomCfJnxTQDKnSxCEBtD5dvZdNgTzC3CqeyWUyU349PBA9Wf = n.GetStringValue(); } },
                { "custom.cf_UpyNBvr6Rw8UBHh7zRboL3PYhbOVJl3XvwgPm3jg64S", n => { CustomCfUpyNBvr6Rw8UBHh7zRboL3PYhbOVJl3XvwgPm3jg64S = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "custom_object_type_id", n => { CustomObjectTypeId = n.GetStringValue(); } },
                { "lead_id", n => { LeadId = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("custom.cf_cSh3fWT3rEJ1BFSezme2YAG6bPrZV5wUWKKrW4iN19g", CustomCfCSh3fWT3rEJ1BFSezme2YAG6bPrZV5wUWKKrW4iN19g);
            writer.WriteStringValue("custom.cf_jnxTQDKnSxCEBtD5dvZdNgTzC3CqeyWUyU349PBA9Wf", CustomCfJnxTQDKnSxCEBtD5dvZdNgTzC3CqeyWUyU349PBA9Wf);
            writer.WriteCollectionOfPrimitiveValues<string>("custom.cf_UpyNBvr6Rw8UBHh7zRboL3PYhbOVJl3XvwgPm3jg64S", CustomCfUpyNBvr6Rw8UBHh7zRboL3PYhbOVJl3XvwgPm3jg64S);
            writer.WriteStringValue("custom_object_type_id", CustomObjectTypeId);
            writer.WriteStringValue("lead_id", LeadId);
            writer.WriteStringValue("name", Name);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
