// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Close.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ImportantThreadReason
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "manual")]
        #pragma warning disable CS1591
        Manual,
        #pragma warning restore CS1591
        [EnumMember(Value = "contains-manual-message")]
        #pragma warning disable CS1591
        ContainsManualMessage,
        #pragma warning restore CS1591
        [EnumMember(Value = "most-recent-communication")]
        #pragma warning disable CS1591
        MostRecentCommunication,
        #pragma warning restore CS1591
        [EnumMember(Value = "has-response")]
        #pragma warning disable CS1591
        HasResponse,
        #pragma warning restore CS1591
        [EnumMember(Value = "whitelisted")]
        #pragma warning disable CS1591
        Whitelisted,
        #pragma warning restore CS1591
        [EnumMember(Value = "by-default")]
        #pragma warning disable CS1591
        ByDefault,
        #pragma warning restore CS1591
        [EnumMember(Value = "unset-initial-default")]
        #pragma warning disable CS1591
        UnsetInitialDefault,
        #pragma warning restore CS1591
    }
}
