// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Close.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class LeadsCreateRequest : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The addresses property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Close.OpenApiClient.Models.LeadsCreateRequestAddressesItem>? Addresses { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Close.OpenApiClient.Models.LeadsCreateRequestAddressesItem> Addresses { get; set; }
#endif
        /// <summary>The contacts property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Close.OpenApiClient.Models.LeadsCreateRequestContactsItem>? Contacts { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Close.OpenApiClient.Models.LeadsCreateRequestContactsItem> Contacts { get; set; }
#endif
        /// <summary>The customCf_bA7SU4vqaefQLuK5UjZMVpbfHK4SVujTJ9unKCIlTvI property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CustomCfBA7SU4vqaefQLuK5UjZMVpbfHK4SVujTJ9unKCIlTvI { get; set; }
#nullable restore
#else
        public string CustomCfBA7SU4vqaefQLuK5UjZMVpbfHK4SVujTJ9unKCIlTvI { get; set; }
#endif
        /// <summary>The customCf_FSYEbxYJFsnY9tN1OTAPIF33j7Sw5Lb7Eawll7JzoNh property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CustomCfFSYEbxYJFsnY9tN1OTAPIF33j7Sw5Lb7Eawll7JzoNh { get; set; }
#nullable restore
#else
        public string CustomCfFSYEbxYJFsnY9tN1OTAPIF33j7Sw5Lb7Eawll7JzoNh { get; set; }
#endif
        /// <summary>The customCf_nenE344jkwrjyRRezwsf8b4V1MCoXWIDHIStmFavZks property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? CustomCfNenE344jkwrjyRRezwsf8b4V1MCoXWIDHIStmFavZks { get; set; }
#nullable restore
#else
        public List<string> CustomCfNenE344jkwrjyRRezwsf8b4V1MCoXWIDHIStmFavZks { get; set; }
#endif
        /// <summary>The customCf_ORxgoOQ5YH1p7lDQzFJ88b4z0j7PLLTRaG66m8bmcKv property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CustomCfORxgoOQ5YH1p7lDQzFJ88b4z0j7PLLTRaG66m8bmcKv { get; set; }
#nullable restore
#else
        public string CustomCfORxgoOQ5YH1p7lDQzFJ88b4z0j7PLLTRaG66m8bmcKv { get; set; }
#endif
        /// <summary>The description property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The status_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StatusId { get; set; }
#nullable restore
#else
        public string StatusId { get; set; }
#endif
        /// <summary>The url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Url { get; set; }
#nullable restore
#else
        public string Url { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Close.OpenApiClient.Models.LeadsCreateRequest"/> and sets the default values.
        /// </summary>
        public LeadsCreateRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Close.OpenApiClient.Models.LeadsCreateRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Close.OpenApiClient.Models.LeadsCreateRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Close.OpenApiClient.Models.LeadsCreateRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "addresses", n => { Addresses = n.GetCollectionOfObjectValues<global::Soenneker.Close.OpenApiClient.Models.LeadsCreateRequestAddressesItem>(global::Soenneker.Close.OpenApiClient.Models.LeadsCreateRequestAddressesItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "contacts", n => { Contacts = n.GetCollectionOfObjectValues<global::Soenneker.Close.OpenApiClient.Models.LeadsCreateRequestContactsItem>(global::Soenneker.Close.OpenApiClient.Models.LeadsCreateRequestContactsItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "custom.cf_bA7SU4vqaefQLuK5UjZMVpbfHK4SVujTJ9unKCIlTvI", n => { CustomCfBA7SU4vqaefQLuK5UjZMVpbfHK4SVujTJ9unKCIlTvI = n.GetStringValue(); } },
                { "custom.cf_FSYEbxYJFsnY9tN1OTAPIF33j7Sw5Lb7Eawll7JzoNh", n => { CustomCfFSYEbxYJFsnY9tN1OTAPIF33j7Sw5Lb7Eawll7JzoNh = n.GetStringValue(); } },
                { "custom.cf_nenE344jkwrjyRRezwsf8b4V1MCoXWIDHIStmFavZks", n => { CustomCfNenE344jkwrjyRRezwsf8b4V1MCoXWIDHIStmFavZks = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "custom.cf_ORxgoOQ5YH1p7lDQzFJ88b4z0j7PLLTRaG66m8bmcKv", n => { CustomCfORxgoOQ5YH1p7lDQzFJ88b4z0j7PLLTRaG66m8bmcKv = n.GetStringValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "status_id", n => { StatusId = n.GetStringValue(); } },
                { "url", n => { Url = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.Close.OpenApiClient.Models.LeadsCreateRequestAddressesItem>("addresses", Addresses);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Close.OpenApiClient.Models.LeadsCreateRequestContactsItem>("contacts", Contacts);
            writer.WriteStringValue("custom.cf_bA7SU4vqaefQLuK5UjZMVpbfHK4SVujTJ9unKCIlTvI", CustomCfBA7SU4vqaefQLuK5UjZMVpbfHK4SVujTJ9unKCIlTvI);
            writer.WriteStringValue("custom.cf_FSYEbxYJFsnY9tN1OTAPIF33j7Sw5Lb7Eawll7JzoNh", CustomCfFSYEbxYJFsnY9tN1OTAPIF33j7Sw5Lb7Eawll7JzoNh);
            writer.WriteCollectionOfPrimitiveValues<string>("custom.cf_nenE344jkwrjyRRezwsf8b4V1MCoXWIDHIStmFavZks", CustomCfNenE344jkwrjyRRezwsf8b4V1MCoXWIDHIStmFavZks);
            writer.WriteStringValue("custom.cf_ORxgoOQ5YH1p7lDQzFJ88b4z0j7PLLTRaG66m8bmcKv", CustomCfORxgoOQ5YH1p7lDQzFJ88b4z0j7PLLTRaG66m8bmcKv);
            writer.WriteStringValue("description", Description);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("status_id", StatusId);
            writer.WriteStringValue("url", Url);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
