// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Close.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum MeetingStatus
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "upcoming")]
        #pragma warning disable CS1591
        Upcoming,
        #pragma warning restore CS1591
        [EnumMember(Value = "in-progress")]
        #pragma warning disable CS1591
        InProgress,
        #pragma warning restore CS1591
        [EnumMember(Value = "completed")]
        #pragma warning disable CS1591
        Completed,
        #pragma warning restore CS1591
        [EnumMember(Value = "canceled")]
        #pragma warning disable CS1591
        Canceled,
        #pragma warning restore CS1591
        [EnumMember(Value = "declined-by-org")]
        #pragma warning disable CS1591
        DeclinedByOrg,
        #pragma warning restore CS1591
        [EnumMember(Value = "declined-by-lead")]
        #pragma warning disable CS1591
        DeclinedByLead,
        #pragma warning restore CS1591
    }
}
