// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Close.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class MeetingTranscriptSpeaker : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The speaker_label property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SpeakerLabel { get; set; }
#nullable restore
#else
        public string SpeakerLabel { get; set; }
#endif
        /// <summary>The speaker_side property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Close.OpenApiClient.Models.SpeakerSideWrapper? SpeakerSide { get; set; }
#nullable restore
#else
        public global::Soenneker.Close.OpenApiClient.Models.SpeakerSideWrapper SpeakerSide { get; set; }
#endif
        /// <summary>The talk_percentage property</summary>
        public double? TalkPercentage { get; set; }
        /// <summary>The talk_time property</summary>
        public double? TalkTime { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Close.OpenApiClient.Models.MeetingTranscriptSpeaker"/> and sets the default values.
        /// </summary>
        public MeetingTranscriptSpeaker()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Close.OpenApiClient.Models.MeetingTranscriptSpeaker"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Close.OpenApiClient.Models.MeetingTranscriptSpeaker CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Close.OpenApiClient.Models.MeetingTranscriptSpeaker();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "speaker_label", n => { SpeakerLabel = n.GetStringValue(); } },
                { "speaker_side", n => { SpeakerSide = n.GetObjectValue<global::Soenneker.Close.OpenApiClient.Models.SpeakerSideWrapper>(global::Soenneker.Close.OpenApiClient.Models.SpeakerSideWrapper.CreateFromDiscriminatorValue); } },
                { "talk_percentage", n => { TalkPercentage = n.GetDoubleValue(); } },
                { "talk_time", n => { TalkTime = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("speaker_label", SpeakerLabel);
            writer.WriteObjectValue<global::Soenneker.Close.OpenApiClient.Models.SpeakerSideWrapper>("speaker_side", SpeakerSide);
            writer.WriteDoubleValue("talk_percentage", TalkPercentage);
            writer.WriteDoubleValue("talk_time", TalkTime);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
