// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Close.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class MeetingActivity : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The activity_at property</summary>
        public DateTimeOffset? ActivityAt { get; set; }
        /// <summary>The actual_duration property</summary>
        public int? ActualDuration { get; set; }
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The attached_call_ids property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? AttachedCallIds { get; set; }
#nullable restore
#else
        public List<string> AttachedCallIds { get; set; }
#endif
        /// <summary>The attendees property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Close.OpenApiClient.Models.MeetingAttendee>? Attendees { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Close.OpenApiClient.Models.MeetingAttendee> Attendees { get; set; }
#endif
        /// <summary>The calendar_event_link property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CalendarEventLink { get; set; }
#nullable restore
#else
        public string CalendarEventLink { get; set; }
#endif
        /// <summary>The calendar_event_uids property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? CalendarEventUids { get; set; }
#nullable restore
#else
        public List<string> CalendarEventUids { get; set; }
#endif
        /// <summary>The comment_summary property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Close.OpenApiClient.Models.CommentSummary? CommentSummary { get; set; }
#nullable restore
#else
        public global::Soenneker.Close.OpenApiClient.Models.CommentSummary CommentSummary { get; set; }
#endif
        /// <summary>The conference_links property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Close.OpenApiClient.Models.MeetingConferenceLink>? ConferenceLinks { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Close.OpenApiClient.Models.MeetingConferenceLink> ConferenceLinks { get; set; }
#endif
        /// <summary>The connected_account_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ConnectedAccountId { get; set; }
#nullable restore
#else
        public string ConnectedAccountId { get; set; }
#endif
        /// <summary>The contact_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ContactId { get; set; }
#nullable restore
#else
        public string ContactId { get; set; }
#endif
        /// <summary>The conversation_type_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ConversationTypeId { get; set; }
#nullable restore
#else
        public string ConversationTypeId { get; set; }
#endif
        /// <summary>The conversation_type_reason property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Close.OpenApiClient.Models.PlaybookReasonWrapper? ConversationTypeReason { get; set; }
#nullable restore
#else
        public global::Soenneker.Close.OpenApiClient.Models.PlaybookReasonWrapper ConversationTypeReason { get; set; }
#endif
        /// <summary>The created_by property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedBy { get; set; }
#nullable restore
#else
        public string CreatedBy { get; set; }
#endif
        /// <summary>The created_by_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedByName { get; set; }
#nullable restore
#else
        public string CreatedByName { get; set; }
#endif
        /// <summary>The date_created property</summary>
        public DateTimeOffset? DateCreated { get; set; }
        /// <summary>The date_updated property</summary>
        public DateTimeOffset? DateUpdated { get; set; }
        /// <summary>The duration property</summary>
        public int? Duration { get; set; }
        /// <summary>The ends_at property</summary>
        public DateTimeOffset? EndsAt { get; set; }
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The integrations property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Close.OpenApiClient.Models.MeetingActivityIntegrationsItemProperty>? Integrations { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Close.OpenApiClient.Models.MeetingActivityIntegrationsItemProperty> Integrations { get; set; }
#endif
        /// <summary>The is_recurring property</summary>
        public bool? IsRecurring { get; set; }
        /// <summary>The lead_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LeadId { get; set; }
#nullable restore
#else
        public string LeadId { get; set; }
#endif
        /// <summary>The location property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Location { get; set; }
#nullable restore
#else
        public string Location { get; set; }
#endif
        /// <summary>The note property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Note { get; set; }
#nullable restore
#else
        public string Note { get; set; }
#endif
        /// <summary>The notetaker_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NotetakerId { get; set; }
#nullable restore
#else
        public string NotetakerId { get; set; }
#endif
        /// <summary>The organization_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OrganizationId { get; set; }
#nullable restore
#else
        public string OrganizationId { get; set; }
#endif
        /// <summary>The outcome_autofill_confidence property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Close.OpenApiClient.Models.OutcomeAutofillConfidenceWrapper? OutcomeAutofillConfidence { get; set; }
#nullable restore
#else
        public global::Soenneker.Close.OpenApiClient.Models.OutcomeAutofillConfidenceWrapper OutcomeAutofillConfidence { get; set; }
#endif
        /// <summary>The outcome_autofill_reasoning property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OutcomeAutofillReasoning { get; set; }
#nullable restore
#else
        public string OutcomeAutofillReasoning { get; set; }
#endif
        /// <summary>The outcome_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OutcomeId { get; set; }
#nullable restore
#else
        public string OutcomeId { get; set; }
#endif
        /// <summary>The outcome_reason property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Close.OpenApiClient.Models.OutcomeReasonWrapper? OutcomeReason { get; set; }
#nullable restore
#else
        public global::Soenneker.Close.OpenApiClient.Models.OutcomeReasonWrapper OutcomeReason { get; set; }
#endif
        /// <summary>The paused_subscriptions property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Close.OpenApiClient.Models.MeetingPausedSubscription>? PausedSubscriptions { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Close.OpenApiClient.Models.MeetingPausedSubscription> PausedSubscriptions { get; set; }
#endif
        /// <summary>The playbook_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PlaybookId { get; set; }
#nullable restore
#else
        public string PlaybookId { get; set; }
#endif
        /// <summary>The playbook_reason property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Close.OpenApiClient.Models.PlaybookReasonWrapper2? PlaybookReason { get; set; }
#nullable restore
#else
        public global::Soenneker.Close.OpenApiClient.Models.PlaybookReasonWrapper2 PlaybookReason { get; set; }
#endif
        /// <summary>The provider_calendar_event_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProviderCalendarEventId { get; set; }
#nullable restore
#else
        public string ProviderCalendarEventId { get; set; }
#endif
        /// <summary>The provider_calendar_ids property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? ProviderCalendarIds { get; set; }
#nullable restore
#else
        public List<string> ProviderCalendarIds { get; set; }
#endif
        /// <summary>The provider_calendar_type property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Close.OpenApiClient.Models.ProviderCalendarTypeWrapper? ProviderCalendarType { get; set; }
#nullable restore
#else
        public global::Soenneker.Close.OpenApiClient.Models.ProviderCalendarTypeWrapper ProviderCalendarType { get; set; }
#endif
        /// <summary>The source property</summary>
        public global::Soenneker.Close.OpenApiClient.Models.MeetingSource? Source { get; set; }
        /// <summary>The starts_at property</summary>
        public DateTimeOffset? StartsAt { get; set; }
        /// <summary>The status property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Close.OpenApiClient.Models.MeetingStatusWrapper? Status { get; set; }
#nullable restore
#else
        public global::Soenneker.Close.OpenApiClient.Models.MeetingStatusWrapper Status { get; set; }
#endif
        /// <summary>The summary property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Close.OpenApiClient.Models.MeetingSummary? Summary { get; set; }
#nullable restore
#else
        public global::Soenneker.Close.OpenApiClient.Models.MeetingSummary Summary { get; set; }
#endif
        /// <summary>The title property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>The transcripts property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Close.OpenApiClient.Models.MeetingTranscript>? Transcripts { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Close.OpenApiClient.Models.MeetingTranscript> Transcripts { get; set; }
#endif
        /// <summary>The type property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Type { get; set; }
#nullable restore
#else
        public string Type { get; set; }
#endif
        /// <summary>The updated_by property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UpdatedBy { get; set; }
#nullable restore
#else
        public string UpdatedBy { get; set; }
#endif
        /// <summary>The updated_by_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UpdatedByName { get; set; }
#nullable restore
#else
        public string UpdatedByName { get; set; }
#endif
        /// <summary>The user_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UserId { get; set; }
#nullable restore
#else
        public string UserId { get; set; }
#endif
        /// <summary>The user_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UserName { get; set; }
#nullable restore
#else
        public string UserName { get; set; }
#endif
        /// <summary>The user_note property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UserNote { get; set; }
#nullable restore
#else
        public string UserNote { get; set; }
#endif
        /// <summary>The user_note_date_updated property</summary>
        public DateTimeOffset? UserNoteDateUpdated { get; set; }
        /// <summary>The user_note_html property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UserNoteHtml { get; set; }
#nullable restore
#else
        public string UserNoteHtml { get; set; }
#endif
        /// <summary>The user_note_mentions property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? UserNoteMentions { get; set; }
#nullable restore
#else
        public List<string> UserNoteMentions { get; set; }
#endif
        /// <summary>The users property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Users { get; set; }
#nullable restore
#else
        public List<string> Users { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Close.OpenApiClient.Models.MeetingActivity"/> and sets the default values.
        /// </summary>
        public MeetingActivity()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Close.OpenApiClient.Models.MeetingActivity"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Close.OpenApiClient.Models.MeetingActivity CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Close.OpenApiClient.Models.MeetingActivity();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "activity_at", n => { ActivityAt = n.GetDateTimeOffsetValue(); } },
                { "actual_duration", n => { ActualDuration = n.GetIntValue(); } },
                { "attached_call_ids", n => { AttachedCallIds = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "attendees", n => { Attendees = n.GetCollectionOfObjectValues<global::Soenneker.Close.OpenApiClient.Models.MeetingAttendee>(global::Soenneker.Close.OpenApiClient.Models.MeetingAttendee.CreateFromDiscriminatorValue)?.AsList(); } },
                { "calendar_event_link", n => { CalendarEventLink = n.GetStringValue(); } },
                { "calendar_event_uids", n => { CalendarEventUids = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "comment_summary", n => { CommentSummary = n.GetObjectValue<global::Soenneker.Close.OpenApiClient.Models.CommentSummary>(global::Soenneker.Close.OpenApiClient.Models.CommentSummary.CreateFromDiscriminatorValue); } },
                { "conference_links", n => { ConferenceLinks = n.GetCollectionOfObjectValues<global::Soenneker.Close.OpenApiClient.Models.MeetingConferenceLink>(global::Soenneker.Close.OpenApiClient.Models.MeetingConferenceLink.CreateFromDiscriminatorValue)?.AsList(); } },
                { "connected_account_id", n => { ConnectedAccountId = n.GetStringValue(); } },
                { "contact_id", n => { ContactId = n.GetStringValue(); } },
                { "conversation_type_id", n => { ConversationTypeId = n.GetStringValue(); } },
                { "conversation_type_reason", n => { ConversationTypeReason = n.GetObjectValue<global::Soenneker.Close.OpenApiClient.Models.PlaybookReasonWrapper>(global::Soenneker.Close.OpenApiClient.Models.PlaybookReasonWrapper.CreateFromDiscriminatorValue); } },
                { "created_by", n => { CreatedBy = n.GetStringValue(); } },
                { "created_by_name", n => { CreatedByName = n.GetStringValue(); } },
                { "date_created", n => { DateCreated = n.GetDateTimeOffsetValue(); } },
                { "date_updated", n => { DateUpdated = n.GetDateTimeOffsetValue(); } },
                { "duration", n => { Duration = n.GetIntValue(); } },
                { "ends_at", n => { EndsAt = n.GetDateTimeOffsetValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "integrations", n => { Integrations = n.GetCollectionOfObjectValues<global::Soenneker.Close.OpenApiClient.Models.MeetingActivityIntegrationsItemProperty>(global::Soenneker.Close.OpenApiClient.Models.MeetingActivityIntegrationsItemProperty.CreateFromDiscriminatorValue)?.AsList(); } },
                { "is_recurring", n => { IsRecurring = n.GetBoolValue(); } },
                { "lead_id", n => { LeadId = n.GetStringValue(); } },
                { "location", n => { Location = n.GetStringValue(); } },
                { "note", n => { Note = n.GetStringValue(); } },
                { "notetaker_id", n => { NotetakerId = n.GetStringValue(); } },
                { "organization_id", n => { OrganizationId = n.GetStringValue(); } },
                { "outcome_autofill_confidence", n => { OutcomeAutofillConfidence = n.GetObjectValue<global::Soenneker.Close.OpenApiClient.Models.OutcomeAutofillConfidenceWrapper>(global::Soenneker.Close.OpenApiClient.Models.OutcomeAutofillConfidenceWrapper.CreateFromDiscriminatorValue); } },
                { "outcome_autofill_reasoning", n => { OutcomeAutofillReasoning = n.GetStringValue(); } },
                { "outcome_id", n => { OutcomeId = n.GetStringValue(); } },
                { "outcome_reason", n => { OutcomeReason = n.GetObjectValue<global::Soenneker.Close.OpenApiClient.Models.OutcomeReasonWrapper>(global::Soenneker.Close.OpenApiClient.Models.OutcomeReasonWrapper.CreateFromDiscriminatorValue); } },
                { "_paused_subscriptions", n => { PausedSubscriptions = n.GetCollectionOfObjectValues<global::Soenneker.Close.OpenApiClient.Models.MeetingPausedSubscription>(global::Soenneker.Close.OpenApiClient.Models.MeetingPausedSubscription.CreateFromDiscriminatorValue)?.AsList(); } },
                { "playbook_id", n => { PlaybookId = n.GetStringValue(); } },
                { "playbook_reason", n => { PlaybookReason = n.GetObjectValue<global::Soenneker.Close.OpenApiClient.Models.PlaybookReasonWrapper2>(global::Soenneker.Close.OpenApiClient.Models.PlaybookReasonWrapper2.CreateFromDiscriminatorValue); } },
                { "provider_calendar_event_id", n => { ProviderCalendarEventId = n.GetStringValue(); } },
                { "provider_calendar_ids", n => { ProviderCalendarIds = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "provider_calendar_type", n => { ProviderCalendarType = n.GetObjectValue<global::Soenneker.Close.OpenApiClient.Models.ProviderCalendarTypeWrapper>(global::Soenneker.Close.OpenApiClient.Models.ProviderCalendarTypeWrapper.CreateFromDiscriminatorValue); } },
                { "source", n => { Source = n.GetEnumValue<global::Soenneker.Close.OpenApiClient.Models.MeetingSource>(); } },
                { "starts_at", n => { StartsAt = n.GetDateTimeOffsetValue(); } },
                { "status", n => { Status = n.GetObjectValue<global::Soenneker.Close.OpenApiClient.Models.MeetingStatusWrapper>(global::Soenneker.Close.OpenApiClient.Models.MeetingStatusWrapper.CreateFromDiscriminatorValue); } },
                { "summary", n => { Summary = n.GetObjectValue<global::Soenneker.Close.OpenApiClient.Models.MeetingSummary>(global::Soenneker.Close.OpenApiClient.Models.MeetingSummary.CreateFromDiscriminatorValue); } },
                { "title", n => { Title = n.GetStringValue(); } },
                { "transcripts", n => { Transcripts = n.GetCollectionOfObjectValues<global::Soenneker.Close.OpenApiClient.Models.MeetingTranscript>(global::Soenneker.Close.OpenApiClient.Models.MeetingTranscript.CreateFromDiscriminatorValue)?.AsList(); } },
                { "_type", n => { Type = n.GetStringValue(); } },
                { "updated_by", n => { UpdatedBy = n.GetStringValue(); } },
                { "updated_by_name", n => { UpdatedByName = n.GetStringValue(); } },
                { "user_id", n => { UserId = n.GetStringValue(); } },
                { "user_name", n => { UserName = n.GetStringValue(); } },
                { "user_note", n => { UserNote = n.GetStringValue(); } },
                { "user_note_date_updated", n => { UserNoteDateUpdated = n.GetDateTimeOffsetValue(); } },
                { "user_note_html", n => { UserNoteHtml = n.GetStringValue(); } },
                { "user_note_mentions", n => { UserNoteMentions = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "users", n => { Users = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("activity_at", ActivityAt);
            writer.WriteIntValue("actual_duration", ActualDuration);
            writer.WriteCollectionOfPrimitiveValues<string>("attached_call_ids", AttachedCallIds);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Close.OpenApiClient.Models.MeetingAttendee>("attendees", Attendees);
            writer.WriteStringValue("calendar_event_link", CalendarEventLink);
            writer.WriteCollectionOfPrimitiveValues<string>("calendar_event_uids", CalendarEventUids);
            writer.WriteObjectValue<global::Soenneker.Close.OpenApiClient.Models.CommentSummary>("comment_summary", CommentSummary);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Close.OpenApiClient.Models.MeetingConferenceLink>("conference_links", ConferenceLinks);
            writer.WriteStringValue("connected_account_id", ConnectedAccountId);
            writer.WriteStringValue("contact_id", ContactId);
            writer.WriteStringValue("conversation_type_id", ConversationTypeId);
            writer.WriteObjectValue<global::Soenneker.Close.OpenApiClient.Models.PlaybookReasonWrapper>("conversation_type_reason", ConversationTypeReason);
            writer.WriteStringValue("created_by", CreatedBy);
            writer.WriteStringValue("created_by_name", CreatedByName);
            writer.WriteDateTimeOffsetValue("date_created", DateCreated);
            writer.WriteDateTimeOffsetValue("date_updated", DateUpdated);
            writer.WriteIntValue("duration", Duration);
            writer.WriteDateTimeOffsetValue("ends_at", EndsAt);
            writer.WriteStringValue("id", Id);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Close.OpenApiClient.Models.MeetingActivityIntegrationsItemProperty>("integrations", Integrations);
            writer.WriteBoolValue("is_recurring", IsRecurring);
            writer.WriteStringValue("lead_id", LeadId);
            writer.WriteStringValue("location", Location);
            writer.WriteStringValue("note", Note);
            writer.WriteStringValue("notetaker_id", NotetakerId);
            writer.WriteStringValue("organization_id", OrganizationId);
            writer.WriteObjectValue<global::Soenneker.Close.OpenApiClient.Models.OutcomeAutofillConfidenceWrapper>("outcome_autofill_confidence", OutcomeAutofillConfidence);
            writer.WriteStringValue("outcome_autofill_reasoning", OutcomeAutofillReasoning);
            writer.WriteStringValue("outcome_id", OutcomeId);
            writer.WriteObjectValue<global::Soenneker.Close.OpenApiClient.Models.OutcomeReasonWrapper>("outcome_reason", OutcomeReason);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Close.OpenApiClient.Models.MeetingPausedSubscription>("_paused_subscriptions", PausedSubscriptions);
            writer.WriteStringValue("playbook_id", PlaybookId);
            writer.WriteObjectValue<global::Soenneker.Close.OpenApiClient.Models.PlaybookReasonWrapper2>("playbook_reason", PlaybookReason);
            writer.WriteStringValue("provider_calendar_event_id", ProviderCalendarEventId);
            writer.WriteCollectionOfPrimitiveValues<string>("provider_calendar_ids", ProviderCalendarIds);
            writer.WriteObjectValue<global::Soenneker.Close.OpenApiClient.Models.ProviderCalendarTypeWrapper>("provider_calendar_type", ProviderCalendarType);
            writer.WriteEnumValue<global::Soenneker.Close.OpenApiClient.Models.MeetingSource>("source", Source);
            writer.WriteDateTimeOffsetValue("starts_at", StartsAt);
            writer.WriteObjectValue<global::Soenneker.Close.OpenApiClient.Models.MeetingStatusWrapper>("status", Status);
            writer.WriteObjectValue<global::Soenneker.Close.OpenApiClient.Models.MeetingSummary>("summary", Summary);
            writer.WriteStringValue("title", Title);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Close.OpenApiClient.Models.MeetingTranscript>("transcripts", Transcripts);
            writer.WriteStringValue("_type", Type);
            writer.WriteStringValue("updated_by", UpdatedBy);
            writer.WriteStringValue("updated_by_name", UpdatedByName);
            writer.WriteStringValue("user_id", UserId);
            writer.WriteStringValue("user_name", UserName);
            writer.WriteStringValue("user_note", UserNote);
            writer.WriteDateTimeOffsetValue("user_note_date_updated", UserNoteDateUpdated);
            writer.WriteStringValue("user_note_html", UserNoteHtml);
            writer.WriteCollectionOfPrimitiveValues<string>("user_note_mentions", UserNoteMentions);
            writer.WriteCollectionOfPrimitiveValues<string>("users", Users);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
