// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Close.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum OutcomeAppliesTo
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "calls")]
        #pragma warning disable CS1591
        Calls,
        #pragma warning restore CS1591
        [EnumMember(Value = "meetings")]
        #pragma warning disable CS1591
        Meetings,
        #pragma warning restore CS1591
    }
}
