// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Close.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum OutcomeReason
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "autofilled")]
        #pragma warning disable CS1591
        Autofilled,
        #pragma warning restore CS1591
        [EnumMember(Value = "user-selected")]
        #pragma warning disable CS1591
        UserSelected,
        #pragma warning restore CS1591
        [EnumMember(Value = "voicemail-dropped")]
        #pragma warning disable CS1591
        VoicemailDropped,
        #pragma warning restore CS1591
    }
}
