// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Close.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum Permission
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "manage_organization")]
        #pragma warning disable CS1591
        ManageOrganization,
        #pragma warning restore CS1591
        [EnumMember(Value = "manage_customizations")]
        #pragma warning disable CS1591
        ManageCustomizations,
        #pragma warning restore CS1591
        [EnumMember(Value = "manage_group_numbers")]
        #pragma warning disable CS1591
        ManageGroupNumbers,
        #pragma warning restore CS1591
        [EnumMember(Value = "manage_team_smart_views")]
        #pragma warning disable CS1591
        ManageTeamSmartViews,
        #pragma warning restore CS1591
        [EnumMember(Value = "manage_team_email_templates")]
        #pragma warning disable CS1591
        ManageTeamEmailTemplates,
        #pragma warning restore CS1591
        [EnumMember(Value = "manage_email_sequences")]
        #pragma warning disable CS1591
        ManageEmailSequences,
        #pragma warning restore CS1591
        [EnumMember(Value = "ai_enrich")]
        #pragma warning disable CS1591
        AiEnrich,
        #pragma warning restore CS1591
        [EnumMember(Value = "bulk_import")]
        #pragma warning disable CS1591
        BulkImport,
        #pragma warning restore CS1591
        [EnumMember(Value = "bulk_email")]
        #pragma warning disable CS1591
        BulkEmail,
        #pragma warning restore CS1591
        [EnumMember(Value = "bulk_enrich")]
        #pragma warning disable CS1591
        BulkEnrich,
        #pragma warning restore CS1591
        [EnumMember(Value = "bulk_sequence_subscriptions")]
        #pragma warning disable CS1591
        BulkSequenceSubscriptions,
        #pragma warning restore CS1591
        [EnumMember(Value = "bulk_edit")]
        #pragma warning disable CS1591
        BulkEdit,
        #pragma warning restore CS1591
        [EnumMember(Value = "bulk_delete")]
        #pragma warning disable CS1591
        BulkDelete,
        #pragma warning restore CS1591
        [EnumMember(Value = "export")]
        #pragma warning disable CS1591
        Export,
        #pragma warning restore CS1591
        [EnumMember(Value = "merge_leads")]
        #pragma warning disable CS1591
        MergeLeads,
        #pragma warning restore CS1591
        [EnumMember(Value = "delete_leads")]
        #pragma warning disable CS1591
        DeleteLeads,
        #pragma warning restore CS1591
        [EnumMember(Value = "manage_others_opportunities")]
        #pragma warning disable CS1591
        ManageOthersOpportunities,
        #pragma warning restore CS1591
        [EnumMember(Value = "delete_own_opportunities")]
        #pragma warning disable CS1591
        DeleteOwnOpportunities,
        #pragma warning restore CS1591
        [EnumMember(Value = "manage_others_tasks")]
        #pragma warning disable CS1591
        ManageOthersTasks,
        #pragma warning restore CS1591
        [EnumMember(Value = "delete_own_tasks")]
        #pragma warning disable CS1591
        DeleteOwnTasks,
        #pragma warning restore CS1591
        [EnumMember(Value = "view_voice_agents")]
        #pragma warning disable CS1591
        ViewVoiceAgents,
        #pragma warning restore CS1591
        [EnumMember(Value = "manage_voice_agents")]
        #pragma warning disable CS1591
        ManageVoiceAgents,
        #pragma warning restore CS1591
        [EnumMember(Value = "ai_chat")]
        #pragma warning disable CS1591
        AiChat,
        #pragma warning restore CS1591
        [EnumMember(Value = "manage_chloe_call_tasks")]
        #pragma warning disable CS1591
        ManageChloeCallTasks,
        #pragma warning restore CS1591
        [EnumMember(Value = "manage_others_activities")]
        #pragma warning disable CS1591
        ManageOthersActivities,
        #pragma warning restore CS1591
        [EnumMember(Value = "delete_own_activities")]
        #pragma warning disable CS1591
        DeleteOwnActivities,
        #pragma warning restore CS1591
        [EnumMember(Value = "calling")]
        #pragma warning disable CS1591
        Calling,
        #pragma warning restore CS1591
        [EnumMember(Value = "call_coach_listen")]
        #pragma warning disable CS1591
        CallCoachListen,
        #pragma warning restore CS1591
        [EnumMember(Value = "call_coach_barge")]
        #pragma warning disable CS1591
        CallCoachBarge,
        #pragma warning restore CS1591
        [EnumMember(Value = "view_all_leads")]
        #pragma warning disable CS1591
        ViewAllLeads,
        #pragma warning restore CS1591
        [EnumMember(Value = "manage_web_forms")]
        #pragma warning disable CS1591
        ManageWebForms,
        #pragma warning restore CS1591
    }
}
