// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Close.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PhoneNumber : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The address_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AddressId { get; set; }
#nullable restore
#else
        public string AddressId { get; set; }
#endif
        /// <summary>The bundle_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BundleId { get; set; }
#nullable restore
#else
        public string BundleId { get; set; }
#endif
        /// <summary>The carrier property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Close.OpenApiClient.Models.UnderlyingCarrierWrapper? Carrier { get; set; }
#nullable restore
#else
        public global::Soenneker.Close.OpenApiClient.Models.UnderlyingCarrierWrapper Carrier { get; set; }
#endif
        /// <summary>The carrier_type property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Close.OpenApiClient.Models.CarrierNumberTypeWrapper? CarrierType { get; set; }
#nullable restore
#else
        public global::Soenneker.Close.OpenApiClient.Models.CarrierNumberTypeWrapper CarrierType { get; set; }
#endif
        /// <summary>The country property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Country { get; set; }
#nullable restore
#else
        public string Country { get; set; }
#endif
        /// <summary>The date_created property</summary>
        public DateTimeOffset? DateCreated { get; set; }
        /// <summary>The date_updated property</summary>
        public DateTimeOffset? DateUpdated { get; set; }
        /// <summary>The forward_to property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ForwardTo { get; set; }
#nullable restore
#else
        public string ForwardTo { get; set; }
#endif
        /// <summary>The forward_to_enabled property</summary>
        public bool? ForwardToEnabled { get; set; }
        /// <summary>The forward_to_formatted property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ForwardToFormatted { get; set; }
#nullable restore
#else
        public string ForwardToFormatted { get; set; }
#endif
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Number of seconds we ring this number on inbound calls before moving on (e.g. to voicemail). `null` means the default of 30 seconds is used.</summary>
        public int? InboundRingDuration { get; set; }
        /// <summary>The is_group_number property</summary>
        public bool? IsGroupNumber { get; set; }
        /// <summary>The is_premium property</summary>
        public bool? IsPremium { get; set; }
        /// <summary>The is_verified property</summary>
        public bool? IsVerified { get; set; }
        /// <summary>The label property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Label { get; set; }
#nullable restore
#else
        public string Label { get; set; }
#endif
        /// <summary>The last_billed_price property</summary>
        public double? LastBilledPrice { get; set; }
        /// <summary>The mms_enabled property</summary>
        public bool? MmsEnabled { get; set; }
        /// <summary>The next_billing_on property</summary>
        public DateTimeOffset? NextBillingOn { get; set; }
        /// <summary>The number property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Number { get; set; }
#nullable restore
#else
        public string Number { get; set; }
#endif
        /// <summary>The number_formatted property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NumberFormatted { get; set; }
#nullable restore
#else
        public string NumberFormatted { get; set; }
#endif
        /// <summary>The organization_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OrganizationId { get; set; }
#nullable restore
#else
        public string OrganizationId { get; set; }
#endif
        /// <summary>The participants property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Participants { get; set; }
#nullable restore
#else
        public List<string> Participants { get; set; }
#endif
        /// <summary>The phone_numbers property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? PhoneNumbers { get; set; }
#nullable restore
#else
        public List<string> PhoneNumbers { get; set; }
#endif
        /// <summary>The phone_numbers_formatted property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? PhoneNumbersFormatted { get; set; }
#nullable restore
#else
        public List<string> PhoneNumbersFormatted { get; set; }
#endif
        /// <summary>The press_1_to_accept property</summary>
        public bool? Press1ToAccept { get; set; }
        /// <summary>The sms_enabled property</summary>
        public bool? SmsEnabled { get; set; }
        /// <summary>The supports_mms_to_countries property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? SupportsMmsToCountries { get; set; }
#nullable restore
#else
        public List<string> SupportsMmsToCountries { get; set; }
#endif
        /// <summary>The supports_sms_to_countries property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? SupportsSmsToCountries { get; set; }
#nullable restore
#else
        public List<string> SupportsSmsToCountries { get; set; }
#endif
        /// <summary>The type property</summary>
        public global::Soenneker.Close.OpenApiClient.Models.PhoneNumberType? Type { get; set; }
        /// <summary>The user_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UserId { get; set; }
#nullable restore
#else
        public string UserId { get; set; }
#endif
        /// <summary>The voicemail_greeting_url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? VoicemailGreetingUrl { get; set; }
#nullable restore
#else
        public string VoicemailGreetingUrl { get; set; }
#endif
        /// <summary>The was_ported property</summary>
        public bool? WasPorted { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Close.OpenApiClient.Models.PhoneNumber"/> and sets the default values.
        /// </summary>
        public PhoneNumber()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Close.OpenApiClient.Models.PhoneNumber"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Close.OpenApiClient.Models.PhoneNumber CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Close.OpenApiClient.Models.PhoneNumber();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "address_id", n => { AddressId = n.GetStringValue(); } },
                { "bundle_id", n => { BundleId = n.GetStringValue(); } },
                { "carrier", n => { Carrier = n.GetObjectValue<global::Soenneker.Close.OpenApiClient.Models.UnderlyingCarrierWrapper>(global::Soenneker.Close.OpenApiClient.Models.UnderlyingCarrierWrapper.CreateFromDiscriminatorValue); } },
                { "carrier_type", n => { CarrierType = n.GetObjectValue<global::Soenneker.Close.OpenApiClient.Models.CarrierNumberTypeWrapper>(global::Soenneker.Close.OpenApiClient.Models.CarrierNumberTypeWrapper.CreateFromDiscriminatorValue); } },
                { "country", n => { Country = n.GetStringValue(); } },
                { "date_created", n => { DateCreated = n.GetDateTimeOffsetValue(); } },
                { "date_updated", n => { DateUpdated = n.GetDateTimeOffsetValue(); } },
                { "forward_to", n => { ForwardTo = n.GetStringValue(); } },
                { "forward_to_enabled", n => { ForwardToEnabled = n.GetBoolValue(); } },
                { "forward_to_formatted", n => { ForwardToFormatted = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "inbound_ring_duration", n => { InboundRingDuration = n.GetIntValue(); } },
                { "is_group_number", n => { IsGroupNumber = n.GetBoolValue(); } },
                { "is_premium", n => { IsPremium = n.GetBoolValue(); } },
                { "is_verified", n => { IsVerified = n.GetBoolValue(); } },
                { "label", n => { Label = n.GetStringValue(); } },
                { "last_billed_price", n => { LastBilledPrice = n.GetDoubleValue(); } },
                { "mms_enabled", n => { MmsEnabled = n.GetBoolValue(); } },
                { "next_billing_on", n => { NextBillingOn = n.GetDateTimeOffsetValue(); } },
                { "number", n => { Number = n.GetStringValue(); } },
                { "number_formatted", n => { NumberFormatted = n.GetStringValue(); } },
                { "organization_id", n => { OrganizationId = n.GetStringValue(); } },
                { "participants", n => { Participants = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "phone_numbers", n => { PhoneNumbers = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "phone_numbers_formatted", n => { PhoneNumbersFormatted = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "press_1_to_accept", n => { Press1ToAccept = n.GetBoolValue(); } },
                { "sms_enabled", n => { SmsEnabled = n.GetBoolValue(); } },
                { "supports_mms_to_countries", n => { SupportsMmsToCountries = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "supports_sms_to_countries", n => { SupportsSmsToCountries = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Close.OpenApiClient.Models.PhoneNumberType>(); } },
                { "user_id", n => { UserId = n.GetStringValue(); } },
                { "voicemail_greeting_url", n => { VoicemailGreetingUrl = n.GetStringValue(); } },
                { "was_ported", n => { WasPorted = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("address_id", AddressId);
            writer.WriteStringValue("bundle_id", BundleId);
            writer.WriteObjectValue<global::Soenneker.Close.OpenApiClient.Models.UnderlyingCarrierWrapper>("carrier", Carrier);
            writer.WriteObjectValue<global::Soenneker.Close.OpenApiClient.Models.CarrierNumberTypeWrapper>("carrier_type", CarrierType);
            writer.WriteStringValue("country", Country);
            writer.WriteDateTimeOffsetValue("date_created", DateCreated);
            writer.WriteDateTimeOffsetValue("date_updated", DateUpdated);
            writer.WriteStringValue("forward_to", ForwardTo);
            writer.WriteBoolValue("forward_to_enabled", ForwardToEnabled);
            writer.WriteStringValue("forward_to_formatted", ForwardToFormatted);
            writer.WriteStringValue("id", Id);
            writer.WriteIntValue("inbound_ring_duration", InboundRingDuration);
            writer.WriteBoolValue("is_group_number", IsGroupNumber);
            writer.WriteBoolValue("is_premium", IsPremium);
            writer.WriteBoolValue("is_verified", IsVerified);
            writer.WriteStringValue("label", Label);
            writer.WriteDoubleValue("last_billed_price", LastBilledPrice);
            writer.WriteBoolValue("mms_enabled", MmsEnabled);
            writer.WriteDateTimeOffsetValue("next_billing_on", NextBillingOn);
            writer.WriteStringValue("number", Number);
            writer.WriteStringValue("number_formatted", NumberFormatted);
            writer.WriteStringValue("organization_id", OrganizationId);
            writer.WriteCollectionOfPrimitiveValues<string>("participants", Participants);
            writer.WriteCollectionOfPrimitiveValues<string>("phone_numbers", PhoneNumbers);
            writer.WriteCollectionOfPrimitiveValues<string>("phone_numbers_formatted", PhoneNumbersFormatted);
            writer.WriteBoolValue("press_1_to_accept", Press1ToAccept);
            writer.WriteBoolValue("sms_enabled", SmsEnabled);
            writer.WriteCollectionOfPrimitiveValues<string>("supports_mms_to_countries", SupportsMmsToCountries);
            writer.WriteCollectionOfPrimitiveValues<string>("supports_sms_to_countries", SupportsSmsToCountries);
            writer.WriteEnumValue<global::Soenneker.Close.OpenApiClient.Models.PhoneNumberType>("type", Type);
            writer.WriteStringValue("user_id", UserId);
            writer.WriteStringValue("voicemail_greeting_url", VoicemailGreetingUrl);
            writer.WriteBoolValue("was_ported", WasPorted);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
