// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Close.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ReportingGetOpportunityStatuses200Response : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The status_overview property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Close.OpenApiClient.Models.ReportingGetOpportunityStatuses200ResponseStatusOverviewItem>? StatusOverview { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Close.OpenApiClient.Models.ReportingGetOpportunityStatuses200ResponseStatusOverviewItem> StatusOverview { get; set; }
#endif
        /// <summary>The status_transitions property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Close.OpenApiClient.Models.ReportingGetOpportunityStatuses200ResponseStatusTransitionsItem>? StatusTransitions { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Close.OpenApiClient.Models.ReportingGetOpportunityStatuses200ResponseStatusTransitionsItem> StatusTransitions { get; set; }
#endif
        /// <summary>The status_transitions_summary property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Close.OpenApiClient.Models.ReportingGetOpportunityStatuses200ResponseStatusTransitionsSummaryItem>? StatusTransitionsSummary { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Close.OpenApiClient.Models.ReportingGetOpportunityStatuses200ResponseStatusTransitionsSummaryItem> StatusTransitionsSummary { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Close.OpenApiClient.Models.ReportingGetOpportunityStatuses200Response"/> and sets the default values.
        /// </summary>
        public ReportingGetOpportunityStatuses200Response()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Close.OpenApiClient.Models.ReportingGetOpportunityStatuses200Response"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Close.OpenApiClient.Models.ReportingGetOpportunityStatuses200Response CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Close.OpenApiClient.Models.ReportingGetOpportunityStatuses200Response();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "status_overview", n => { StatusOverview = n.GetCollectionOfObjectValues<global::Soenneker.Close.OpenApiClient.Models.ReportingGetOpportunityStatuses200ResponseStatusOverviewItem>(global::Soenneker.Close.OpenApiClient.Models.ReportingGetOpportunityStatuses200ResponseStatusOverviewItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "status_transitions", n => { StatusTransitions = n.GetCollectionOfObjectValues<global::Soenneker.Close.OpenApiClient.Models.ReportingGetOpportunityStatuses200ResponseStatusTransitionsItem>(global::Soenneker.Close.OpenApiClient.Models.ReportingGetOpportunityStatuses200ResponseStatusTransitionsItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "status_transitions_summary", n => { StatusTransitionsSummary = n.GetCollectionOfObjectValues<global::Soenneker.Close.OpenApiClient.Models.ReportingGetOpportunityStatuses200ResponseStatusTransitionsSummaryItem>(global::Soenneker.Close.OpenApiClient.Models.ReportingGetOpportunityStatuses200ResponseStatusTransitionsSummaryItem.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.Close.OpenApiClient.Models.ReportingGetOpportunityStatuses200ResponseStatusOverviewItem>("status_overview", StatusOverview);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Close.OpenApiClient.Models.ReportingGetOpportunityStatuses200ResponseStatusTransitionsItem>("status_transitions", StatusTransitions);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Close.OpenApiClient.Models.ReportingGetOpportunityStatuses200ResponseStatusTransitionsSummaryItem>("status_transitions_summary", StatusTransitionsSummary);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
