// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Close.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ReportingGetFunnelTotals200ResponseDataItem : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The average_time_to_win property</summary>
        public long? AverageTimeToWin { get; set; }
        /// <summary>The average_value_annualized_per_won_opportunity property</summary>
        public long? AverageValueAnnualizedPerWonOpportunity { get; set; }
        /// <summary>The count property</summary>
        public long? Count { get; set; }
        /// <summary>The count_total_complete property</summary>
        public long? CountTotalComplete { get; set; }
        /// <summary>The count_total_won property</summary>
        public long? CountTotalWon { get; set; }
        /// <summary>The count_win_rate property</summary>
        public long? CountWinRate { get; set; }
        /// <summary>The sales_velocity property</summary>
        public long? SalesVelocity { get; set; }
        /// <summary>The user_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UserId { get; set; }
#nullable restore
#else
        public string UserId { get; set; }
#endif
        /// <summary>The value_total_complete property</summary>
        public long? ValueTotalComplete { get; set; }
        /// <summary>The value_total_won property</summary>
        public long? ValueTotalWon { get; set; }
        /// <summary>The value_win_rate property</summary>
        public long? ValueWinRate { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Close.OpenApiClient.Models.ReportingGetFunnelTotals200ResponseDataItem"/> and sets the default values.
        /// </summary>
        public ReportingGetFunnelTotals200ResponseDataItem()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Close.OpenApiClient.Models.ReportingGetFunnelTotals200ResponseDataItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Close.OpenApiClient.Models.ReportingGetFunnelTotals200ResponseDataItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Close.OpenApiClient.Models.ReportingGetFunnelTotals200ResponseDataItem();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "average_time_to_win", n => { AverageTimeToWin = n.GetLongValue(); } },
                { "average_value_annualized_per_won_opportunity", n => { AverageValueAnnualizedPerWonOpportunity = n.GetLongValue(); } },
                { "count", n => { Count = n.GetLongValue(); } },
                { "count_total_complete", n => { CountTotalComplete = n.GetLongValue(); } },
                { "count_total_won", n => { CountTotalWon = n.GetLongValue(); } },
                { "count_win_rate", n => { CountWinRate = n.GetLongValue(); } },
                { "sales_velocity", n => { SalesVelocity = n.GetLongValue(); } },
                { "user_id", n => { UserId = n.GetStringValue(); } },
                { "value_total_complete", n => { ValueTotalComplete = n.GetLongValue(); } },
                { "value_total_won", n => { ValueTotalWon = n.GetLongValue(); } },
                { "value_win_rate", n => { ValueWinRate = n.GetLongValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteLongValue("average_time_to_win", AverageTimeToWin);
            writer.WriteLongValue("average_value_annualized_per_won_opportunity", AverageValueAnnualizedPerWonOpportunity);
            writer.WriteLongValue("count", Count);
            writer.WriteLongValue("count_total_complete", CountTotalComplete);
            writer.WriteLongValue("count_total_won", CountTotalWon);
            writer.WriteLongValue("count_win_rate", CountWinRate);
            writer.WriteLongValue("sales_velocity", SalesVelocity);
            writer.WriteStringValue("user_id", UserId);
            writer.WriteLongValue("value_total_complete", ValueTotalComplete);
            writer.WriteLongValue("value_total_won", ValueTotalWon);
            writer.WriteLongValue("value_win_rate", ValueWinRate);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
