// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Close.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class RunFieldEnrichment : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The field_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FieldId { get; set; }
#nullable restore
#else
        public string FieldId { get; set; }
#endif
        /// <summary>The object_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ObjectId { get; set; }
#nullable restore
#else
        public string ObjectId { get; set; }
#endif
        /// <summary>The object_type property</summary>
        public global::Soenneker.Close.OpenApiClient.Models.RunFieldEnrichmentObjectType? ObjectType { get; set; }
        /// <summary>The organization_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OrganizationId { get; set; }
#nullable restore
#else
        public string OrganizationId { get; set; }
#endif
        /// <summary>The overwrite_existing_value property</summary>
        public bool? OverwriteExistingValue { get; set; }
        /// <summary>The set_new_value property</summary>
        public bool? SetNewValue { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Close.OpenApiClient.Models.RunFieldEnrichment"/> and sets the default values.
        /// </summary>
        public RunFieldEnrichment()
        {
            OverwriteExistingValue = false;
            SetNewValue = true;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Close.OpenApiClient.Models.RunFieldEnrichment"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Close.OpenApiClient.Models.RunFieldEnrichment CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Close.OpenApiClient.Models.RunFieldEnrichment();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "field_id", n => { FieldId = n.GetStringValue(); } },
                { "object_id", n => { ObjectId = n.GetStringValue(); } },
                { "object_type", n => { ObjectType = n.GetEnumValue<global::Soenneker.Close.OpenApiClient.Models.RunFieldEnrichmentObjectType>(); } },
                { "organization_id", n => { OrganizationId = n.GetStringValue(); } },
                { "overwrite_existing_value", n => { OverwriteExistingValue = n.GetBoolValue(); } },
                { "set_new_value", n => { SetNewValue = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("field_id", FieldId);
            writer.WriteStringValue("object_id", ObjectId);
            writer.WriteEnumValue<global::Soenneker.Close.OpenApiClient.Models.RunFieldEnrichmentObjectType>("object_type", ObjectType);
            writer.WriteStringValue("organization_id", OrganizationId);
            writer.WriteBoolValue("overwrite_existing_value", OverwriteExistingValue);
            writer.WriteBoolValue("set_new_value", SetNewValue);
        }
    }
}
#pragma warning restore CS0618
