// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Close.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SavedSearch : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The date_created property</summary>
        public DateTimeOffset? DateCreated { get; set; }
        /// <summary>The date_updated property</summary>
        public DateTimeOffset? DateUpdated { get; set; }
        /// <summary>The description property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The is_shared property</summary>
        public bool? IsShared { get; set; }
        /// <summary>The is_user_dependent property</summary>
        public bool? IsUserDependent { get; set; }
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The organization_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OrganizationId { get; set; }
#nullable restore
#else
        public string OrganizationId { get; set; }
#endif
        /// <summary>The query property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Query { get; set; }
#nullable restore
#else
        public string Query { get; set; }
#endif
        /// <summary>The selected_fields property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Close.OpenApiClient.Models.SavedSearchSelectedFields? SelectedFields { get; set; }
#nullable restore
#else
        public global::Soenneker.Close.OpenApiClient.Models.SavedSearchSelectedFields SelectedFields { get; set; }
#endif
        /// <summary>The shared_with property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Close.OpenApiClient.Models.SavedSearchSharedWith? SharedWith { get; set; }
#nullable restore
#else
        public global::Soenneker.Close.OpenApiClient.Models.SavedSearchSharedWith SharedWith { get; set; }
#endif
        /// <summary>The sharing_settings property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Close.OpenApiClient.Models.SavedSearchSharingSettings? SharingSettings { get; set; }
#nullable restore
#else
        public global::Soenneker.Close.OpenApiClient.Models.SavedSearchSharingSettings SharingSettings { get; set; }
#endif
        /// <summary>The s_query property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Close.OpenApiClient.Models.SavedSearchSQuery? SQuery { get; set; }
#nullable restore
#else
        public global::Soenneker.Close.OpenApiClient.Models.SavedSearchSQuery SQuery { get; set; }
#endif
        /// <summary>The type property</summary>
        public global::Soenneker.Close.OpenApiClient.Models.SavedSearchType? Type { get; set; }
        /// <summary>The user_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UserId { get; set; }
#nullable restore
#else
        public string UserId { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Close.OpenApiClient.Models.SavedSearch"/> and sets the default values.
        /// </summary>
        public SavedSearch()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Close.OpenApiClient.Models.SavedSearch"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Close.OpenApiClient.Models.SavedSearch CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Close.OpenApiClient.Models.SavedSearch();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "date_created", n => { DateCreated = n.GetDateTimeOffsetValue(); } },
                { "date_updated", n => { DateUpdated = n.GetDateTimeOffsetValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "is_shared", n => { IsShared = n.GetBoolValue(); } },
                { "is_user_dependent", n => { IsUserDependent = n.GetBoolValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "organization_id", n => { OrganizationId = n.GetStringValue(); } },
                { "query", n => { Query = n.GetStringValue(); } },
                { "s_query", n => { SQuery = n.GetObjectValue<global::Soenneker.Close.OpenApiClient.Models.SavedSearchSQuery>(global::Soenneker.Close.OpenApiClient.Models.SavedSearchSQuery.CreateFromDiscriminatorValue); } },
                { "selected_fields", n => { SelectedFields = n.GetObjectValue<global::Soenneker.Close.OpenApiClient.Models.SavedSearchSelectedFields>(global::Soenneker.Close.OpenApiClient.Models.SavedSearchSelectedFields.CreateFromDiscriminatorValue); } },
                { "shared_with", n => { SharedWith = n.GetObjectValue<global::Soenneker.Close.OpenApiClient.Models.SavedSearchSharedWith>(global::Soenneker.Close.OpenApiClient.Models.SavedSearchSharedWith.CreateFromDiscriminatorValue); } },
                { "sharing_settings", n => { SharingSettings = n.GetObjectValue<global::Soenneker.Close.OpenApiClient.Models.SavedSearchSharingSettings>(global::Soenneker.Close.OpenApiClient.Models.SavedSearchSharingSettings.CreateFromDiscriminatorValue); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Close.OpenApiClient.Models.SavedSearchType>(); } },
                { "user_id", n => { UserId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("date_created", DateCreated);
            writer.WriteDateTimeOffsetValue("date_updated", DateUpdated);
            writer.WriteStringValue("description", Description);
            writer.WriteStringValue("id", Id);
            writer.WriteBoolValue("is_shared", IsShared);
            writer.WriteBoolValue("is_user_dependent", IsUserDependent);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("organization_id", OrganizationId);
            writer.WriteStringValue("query", Query);
            writer.WriteObjectValue<global::Soenneker.Close.OpenApiClient.Models.SavedSearchSelectedFields>("selected_fields", SelectedFields);
            writer.WriteObjectValue<global::Soenneker.Close.OpenApiClient.Models.SavedSearchSharedWith>("shared_with", SharedWith);
            writer.WriteObjectValue<global::Soenneker.Close.OpenApiClient.Models.SavedSearchSharingSettings>("sharing_settings", SharingSettings);
            writer.WriteObjectValue<global::Soenneker.Close.OpenApiClient.Models.SavedSearchSQuery>("s_query", SQuery);
            writer.WriteEnumValue<global::Soenneker.Close.OpenApiClient.Models.SavedSearchType>("type", Type);
            writer.WriteStringValue("user_id", UserId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
