// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Close.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class TasksList200ResponseDataItem : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The agent_config_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? AgentConfigId { get; set; }
#nullable restore
#else
        public UntypedNode AgentConfigId { get; set; }
#endif
        /// <summary>The assigned_to property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AssignedTo { get; set; }
#nullable restore
#else
        public string AssignedTo { get; set; }
#endif
        /// <summary>The assigned_to_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AssignedToName { get; set; }
#nullable restore
#else
        public string AssignedToName { get; set; }
#endif
        /// <summary>The attachments property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Close.OpenApiClient.Models.TasksList200ResponseDataItemAttachmentsItem>? Attachments { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Close.OpenApiClient.Models.TasksList200ResponseDataItemAttachmentsItem> Attachments { get; set; }
#endif
        /// <summary>The body_preview property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BodyPreview { get; set; }
#nullable restore
#else
        public string BodyPreview { get; set; }
#endif
        /// <summary>The contact_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ContactId { get; set; }
#nullable restore
#else
        public string ContactId { get; set; }
#endif
        /// <summary>The contact_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ContactName { get; set; }
#nullable restore
#else
        public string ContactName { get; set; }
#endif
        /// <summary>The created_by property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedBy { get; set; }
#nullable restore
#else
        public string CreatedBy { get; set; }
#endif
        /// <summary>The created_by_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedByName { get; set; }
#nullable restore
#else
        public string CreatedByName { get; set; }
#endif
        /// <summary>The date property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Date { get; set; }
#nullable restore
#else
        public string Date { get; set; }
#endif
        /// <summary>The date_created property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DateCreated { get; set; }
#nullable restore
#else
        public string DateCreated { get; set; }
#endif
        /// <summary>The date_updated property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DateUpdated { get; set; }
#nullable restore
#else
        public string DateUpdated { get; set; }
#endif
        /// <summary>The deduplication_key property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? DeduplicationKey { get; set; }
#nullable restore
#else
        public UntypedNode DeduplicationKey { get; set; }
#endif
        /// <summary>The email_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EmailId { get; set; }
#nullable restore
#else
        public string EmailId { get; set; }
#endif
        /// <summary>The emails property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Emails { get; set; }
#nullable restore
#else
        public List<string> Emails { get; set; }
#endif
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The is_complete property</summary>
        public bool? IsComplete { get; set; }
        /// <summary>The is_dateless property</summary>
        public bool? IsDateless { get; set; }
        /// <summary>The is_primary_lead_notification property</summary>
        public bool? IsPrimaryLeadNotification { get; set; }
        /// <summary>The lead_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LeadId { get; set; }
#nullable restore
#else
        public string LeadId { get; set; }
#endif
        /// <summary>The lead_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LeadName { get; set; }
#nullable restore
#else
        public string LeadName { get; set; }
#endif
        /// <summary>The local_phone property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LocalPhone { get; set; }
#nullable restore
#else
        public string LocalPhone { get; set; }
#endif
        /// <summary>The object_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ObjectId { get; set; }
#nullable restore
#else
        public string ObjectId { get; set; }
#endif
        /// <summary>The object_type property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ObjectType { get; set; }
#nullable restore
#else
        public string ObjectType { get; set; }
#endif
        /// <summary>The opportunity_note property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OpportunityNote { get; set; }
#nullable restore
#else
        public string OpportunityNote { get; set; }
#endif
        /// <summary>The opportunity_value property</summary>
        public long? OpportunityValue { get; set; }
        /// <summary>The opportunity_value_currency property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OpportunityValueCurrency { get; set; }
#nullable restore
#else
        public string OpportunityValueCurrency { get; set; }
#endif
        /// <summary>The opportunity_value_formatted property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OpportunityValueFormatted { get; set; }
#nullable restore
#else
        public string OpportunityValueFormatted { get; set; }
#endif
        /// <summary>The opportunity_value_period property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OpportunityValuePeriod { get; set; }
#nullable restore
#else
        public string OpportunityValuePeriod { get; set; }
#endif
        /// <summary>The organization_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OrganizationId { get; set; }
#nullable restore
#else
        public string OrganizationId { get; set; }
#endif
        /// <summary>The phone property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Phone { get; set; }
#nullable restore
#else
        public string Phone { get; set; }
#endif
        /// <summary>The phone_formatted property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PhoneFormatted { get; set; }
#nullable restore
#else
        public string PhoneFormatted { get; set; }
#endif
        /// <summary>The phone_number_description property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PhoneNumberDescription { get; set; }
#nullable restore
#else
        public string PhoneNumberDescription { get; set; }
#endif
        /// <summary>The recording_url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RecordingUrl { get; set; }
#nullable restore
#else
        public string RecordingUrl { get; set; }
#endif
        /// <summary>The remote_phone property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RemotePhone { get; set; }
#nullable restore
#else
        public string RemotePhone { get; set; }
#endif
        /// <summary>The remote_phone_description property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RemotePhoneDescription { get; set; }
#nullable restore
#else
        public string RemotePhoneDescription { get; set; }
#endif
        /// <summary>The remote_phone_formatted property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RemotePhoneFormatted { get; set; }
#nullable restore
#else
        public string RemotePhoneFormatted { get; set; }
#endif
        /// <summary>The resolution property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? Resolution { get; set; }
#nullable restore
#else
        public UntypedNode Resolution { get; set; }
#endif
        /// <summary>The sequence_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SequenceId { get; set; }
#nullable restore
#else
        public string SequenceId { get; set; }
#endif
        /// <summary>The sequence_subscription_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SequenceSubscriptionId { get; set; }
#nullable restore
#else
        public string SequenceSubscriptionId { get; set; }
#endif
        /// <summary>The step_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StepId { get; set; }
#nullable restore
#else
        public string StepId { get; set; }
#endif
        /// <summary>The subject property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Subject { get; set; }
#nullable restore
#else
        public string Subject { get; set; }
#endif
        /// <summary>The text property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Text { get; set; }
#nullable restore
#else
        public string Text { get; set; }
#endif
        /// <summary>The type property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Type { get; set; }
#nullable restore
#else
        public string Type { get; set; }
#endif
        /// <summary>The updated_by property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UpdatedBy { get; set; }
#nullable restore
#else
        public string UpdatedBy { get; set; }
#endif
        /// <summary>The updated_by_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UpdatedByName { get; set; }
#nullable restore
#else
        public string UpdatedByName { get; set; }
#endif
        /// <summary>The view property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? View { get; set; }
#nullable restore
#else
        public string View { get; set; }
#endif
        /// <summary>The voicemail_duration property</summary>
        public long? VoicemailDuration { get; set; }
        /// <summary>The voicemail_url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? VoicemailUrl { get; set; }
#nullable restore
#else
        public string VoicemailUrl { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Close.OpenApiClient.Models.TasksList200ResponseDataItem"/> and sets the default values.
        /// </summary>
        public TasksList200ResponseDataItem()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Close.OpenApiClient.Models.TasksList200ResponseDataItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Close.OpenApiClient.Models.TasksList200ResponseDataItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Close.OpenApiClient.Models.TasksList200ResponseDataItem();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "agent_config_id", n => { AgentConfigId = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "assigned_to", n => { AssignedTo = n.GetStringValue(); } },
                { "assigned_to_name", n => { AssignedToName = n.GetStringValue(); } },
                { "attachments", n => { Attachments = n.GetCollectionOfObjectValues<global::Soenneker.Close.OpenApiClient.Models.TasksList200ResponseDataItemAttachmentsItem>(global::Soenneker.Close.OpenApiClient.Models.TasksList200ResponseDataItemAttachmentsItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "body_preview", n => { BodyPreview = n.GetStringValue(); } },
                { "contact_id", n => { ContactId = n.GetStringValue(); } },
                { "contact_name", n => { ContactName = n.GetStringValue(); } },
                { "created_by", n => { CreatedBy = n.GetStringValue(); } },
                { "created_by_name", n => { CreatedByName = n.GetStringValue(); } },
                { "date", n => { Date = n.GetStringValue(); } },
                { "date_created", n => { DateCreated = n.GetStringValue(); } },
                { "date_updated", n => { DateUpdated = n.GetStringValue(); } },
                { "deduplication_key", n => { DeduplicationKey = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "email_id", n => { EmailId = n.GetStringValue(); } },
                { "emails", n => { Emails = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "is_complete", n => { IsComplete = n.GetBoolValue(); } },
                { "is_dateless", n => { IsDateless = n.GetBoolValue(); } },
                { "is_primary_lead_notification", n => { IsPrimaryLeadNotification = n.GetBoolValue(); } },
                { "lead_id", n => { LeadId = n.GetStringValue(); } },
                { "lead_name", n => { LeadName = n.GetStringValue(); } },
                { "local_phone", n => { LocalPhone = n.GetStringValue(); } },
                { "object_id", n => { ObjectId = n.GetStringValue(); } },
                { "object_type", n => { ObjectType = n.GetStringValue(); } },
                { "opportunity_note", n => { OpportunityNote = n.GetStringValue(); } },
                { "opportunity_value", n => { OpportunityValue = n.GetLongValue(); } },
                { "opportunity_value_currency", n => { OpportunityValueCurrency = n.GetStringValue(); } },
                { "opportunity_value_formatted", n => { OpportunityValueFormatted = n.GetStringValue(); } },
                { "opportunity_value_period", n => { OpportunityValuePeriod = n.GetStringValue(); } },
                { "organization_id", n => { OrganizationId = n.GetStringValue(); } },
                { "phone", n => { Phone = n.GetStringValue(); } },
                { "phone_formatted", n => { PhoneFormatted = n.GetStringValue(); } },
                { "phone_number_description", n => { PhoneNumberDescription = n.GetStringValue(); } },
                { "recording_url", n => { RecordingUrl = n.GetStringValue(); } },
                { "remote_phone", n => { RemotePhone = n.GetStringValue(); } },
                { "remote_phone_description", n => { RemotePhoneDescription = n.GetStringValue(); } },
                { "remote_phone_formatted", n => { RemotePhoneFormatted = n.GetStringValue(); } },
                { "resolution", n => { Resolution = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "sequence_id", n => { SequenceId = n.GetStringValue(); } },
                { "sequence_subscription_id", n => { SequenceSubscriptionId = n.GetStringValue(); } },
                { "step_id", n => { StepId = n.GetStringValue(); } },
                { "subject", n => { Subject = n.GetStringValue(); } },
                { "text", n => { Text = n.GetStringValue(); } },
                { "_type", n => { Type = n.GetStringValue(); } },
                { "updated_by", n => { UpdatedBy = n.GetStringValue(); } },
                { "updated_by_name", n => { UpdatedByName = n.GetStringValue(); } },
                { "view", n => { View = n.GetStringValue(); } },
                { "voicemail_duration", n => { VoicemailDuration = n.GetLongValue(); } },
                { "voicemail_url", n => { VoicemailUrl = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<UntypedNode>("agent_config_id", AgentConfigId);
            writer.WriteStringValue("assigned_to", AssignedTo);
            writer.WriteStringValue("assigned_to_name", AssignedToName);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Close.OpenApiClient.Models.TasksList200ResponseDataItemAttachmentsItem>("attachments", Attachments);
            writer.WriteStringValue("body_preview", BodyPreview);
            writer.WriteStringValue("contact_id", ContactId);
            writer.WriteStringValue("contact_name", ContactName);
            writer.WriteStringValue("created_by", CreatedBy);
            writer.WriteStringValue("created_by_name", CreatedByName);
            writer.WriteStringValue("date", Date);
            writer.WriteStringValue("date_created", DateCreated);
            writer.WriteStringValue("date_updated", DateUpdated);
            writer.WriteObjectValue<UntypedNode>("deduplication_key", DeduplicationKey);
            writer.WriteStringValue("email_id", EmailId);
            writer.WriteCollectionOfPrimitiveValues<string>("emails", Emails);
            writer.WriteStringValue("id", Id);
            writer.WriteBoolValue("is_complete", IsComplete);
            writer.WriteBoolValue("is_dateless", IsDateless);
            writer.WriteBoolValue("is_primary_lead_notification", IsPrimaryLeadNotification);
            writer.WriteStringValue("lead_id", LeadId);
            writer.WriteStringValue("lead_name", LeadName);
            writer.WriteStringValue("local_phone", LocalPhone);
            writer.WriteStringValue("object_id", ObjectId);
            writer.WriteStringValue("object_type", ObjectType);
            writer.WriteStringValue("opportunity_note", OpportunityNote);
            writer.WriteLongValue("opportunity_value", OpportunityValue);
            writer.WriteStringValue("opportunity_value_currency", OpportunityValueCurrency);
            writer.WriteStringValue("opportunity_value_formatted", OpportunityValueFormatted);
            writer.WriteStringValue("opportunity_value_period", OpportunityValuePeriod);
            writer.WriteStringValue("organization_id", OrganizationId);
            writer.WriteStringValue("phone", Phone);
            writer.WriteStringValue("phone_formatted", PhoneFormatted);
            writer.WriteStringValue("phone_number_description", PhoneNumberDescription);
            writer.WriteStringValue("recording_url", RecordingUrl);
            writer.WriteStringValue("remote_phone", RemotePhone);
            writer.WriteStringValue("remote_phone_description", RemotePhoneDescription);
            writer.WriteStringValue("remote_phone_formatted", RemotePhoneFormatted);
            writer.WriteObjectValue<UntypedNode>("resolution", Resolution);
            writer.WriteStringValue("sequence_id", SequenceId);
            writer.WriteStringValue("sequence_subscription_id", SequenceSubscriptionId);
            writer.WriteStringValue("step_id", StepId);
            writer.WriteStringValue("subject", Subject);
            writer.WriteStringValue("text", Text);
            writer.WriteStringValue("_type", Type);
            writer.WriteStringValue("updated_by", UpdatedBy);
            writer.WriteStringValue("updated_by_name", UpdatedByName);
            writer.WriteStringValue("view", View);
            writer.WriteLongValue("voicemail_duration", VoicemailDuration);
            writer.WriteStringValue("voicemail_url", VoicemailUrl);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
