// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Close.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class TaskCompletedActivity : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The activity_at property</summary>
        public DateTimeOffset? ActivityAt { get; set; }
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The comment_summary property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Close.OpenApiClient.Models.CommentSummary? CommentSummary { get; set; }
#nullable restore
#else
        public global::Soenneker.Close.OpenApiClient.Models.CommentSummary CommentSummary { get; set; }
#endif
        /// <summary>The created_by property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedBy { get; set; }
#nullable restore
#else
        public string CreatedBy { get; set; }
#endif
        /// <summary>The created_by_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedByName { get; set; }
#nullable restore
#else
        public string CreatedByName { get; set; }
#endif
        /// <summary>The date_created property</summary>
        public DateTimeOffset? DateCreated { get; set; }
        /// <summary>The date_updated property</summary>
        public DateTimeOffset? DateUpdated { get; set; }
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The lead_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LeadId { get; set; }
#nullable restore
#else
        public string LeadId { get; set; }
#endif
        /// <summary>The organization_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OrganizationId { get; set; }
#nullable restore
#else
        public string OrganizationId { get; set; }
#endif
        /// <summary>The sequence_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SequenceId { get; set; }
#nullable restore
#else
        public string SequenceId { get; set; }
#endif
        /// <summary>The sequence_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SequenceName { get; set; }
#nullable restore
#else
        public string SequenceName { get; set; }
#endif
        /// <summary>The sequence_subscription_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SequenceSubscriptionId { get; set; }
#nullable restore
#else
        public string SequenceSubscriptionId { get; set; }
#endif
        /// <summary>The task_assigned_to property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TaskAssignedTo { get; set; }
#nullable restore
#else
        public string TaskAssignedTo { get; set; }
#endif
        /// <summary>The task_assigned_to_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TaskAssignedToName { get; set; }
#nullable restore
#else
        public string TaskAssignedToName { get; set; }
#endif
        /// <summary>The task_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TaskId { get; set; }
#nullable restore
#else
        public string TaskId { get; set; }
#endif
        /// <summary>The task_text property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TaskText { get; set; }
#nullable restore
#else
        public string TaskText { get; set; }
#endif
        /// <summary>The type property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Type { get; set; }
#nullable restore
#else
        public string Type { get; set; }
#endif
        /// <summary>The updated_by property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UpdatedBy { get; set; }
#nullable restore
#else
        public string UpdatedBy { get; set; }
#endif
        /// <summary>The updated_by_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UpdatedByName { get; set; }
#nullable restore
#else
        public string UpdatedByName { get; set; }
#endif
        /// <summary>The user_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UserId { get; set; }
#nullable restore
#else
        public string UserId { get; set; }
#endif
        /// <summary>The user_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UserName { get; set; }
#nullable restore
#else
        public string UserName { get; set; }
#endif
        /// <summary>The users property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Users { get; set; }
#nullable restore
#else
        public List<string> Users { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Close.OpenApiClient.Models.TaskCompletedActivity"/> and sets the default values.
        /// </summary>
        public TaskCompletedActivity()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Close.OpenApiClient.Models.TaskCompletedActivity"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Close.OpenApiClient.Models.TaskCompletedActivity CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Close.OpenApiClient.Models.TaskCompletedActivity();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "activity_at", n => { ActivityAt = n.GetDateTimeOffsetValue(); } },
                { "comment_summary", n => { CommentSummary = n.GetObjectValue<global::Soenneker.Close.OpenApiClient.Models.CommentSummary>(global::Soenneker.Close.OpenApiClient.Models.CommentSummary.CreateFromDiscriminatorValue); } },
                { "created_by", n => { CreatedBy = n.GetStringValue(); } },
                { "created_by_name", n => { CreatedByName = n.GetStringValue(); } },
                { "date_created", n => { DateCreated = n.GetDateTimeOffsetValue(); } },
                { "date_updated", n => { DateUpdated = n.GetDateTimeOffsetValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "lead_id", n => { LeadId = n.GetStringValue(); } },
                { "organization_id", n => { OrganizationId = n.GetStringValue(); } },
                { "sequence_id", n => { SequenceId = n.GetStringValue(); } },
                { "sequence_name", n => { SequenceName = n.GetStringValue(); } },
                { "sequence_subscription_id", n => { SequenceSubscriptionId = n.GetStringValue(); } },
                { "task_assigned_to", n => { TaskAssignedTo = n.GetStringValue(); } },
                { "task_assigned_to_name", n => { TaskAssignedToName = n.GetStringValue(); } },
                { "task_id", n => { TaskId = n.GetStringValue(); } },
                { "task_text", n => { TaskText = n.GetStringValue(); } },
                { "_type", n => { Type = n.GetStringValue(); } },
                { "updated_by", n => { UpdatedBy = n.GetStringValue(); } },
                { "updated_by_name", n => { UpdatedByName = n.GetStringValue(); } },
                { "user_id", n => { UserId = n.GetStringValue(); } },
                { "user_name", n => { UserName = n.GetStringValue(); } },
                { "users", n => { Users = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("activity_at", ActivityAt);
            writer.WriteObjectValue<global::Soenneker.Close.OpenApiClient.Models.CommentSummary>("comment_summary", CommentSummary);
            writer.WriteStringValue("created_by", CreatedBy);
            writer.WriteStringValue("created_by_name", CreatedByName);
            writer.WriteDateTimeOffsetValue("date_created", DateCreated);
            writer.WriteDateTimeOffsetValue("date_updated", DateUpdated);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("lead_id", LeadId);
            writer.WriteStringValue("organization_id", OrganizationId);
            writer.WriteStringValue("sequence_id", SequenceId);
            writer.WriteStringValue("sequence_name", SequenceName);
            writer.WriteStringValue("sequence_subscription_id", SequenceSubscriptionId);
            writer.WriteStringValue("task_assigned_to", TaskAssignedTo);
            writer.WriteStringValue("task_assigned_to_name", TaskAssignedToName);
            writer.WriteStringValue("task_id", TaskId);
            writer.WriteStringValue("task_text", TaskText);
            writer.WriteStringValue("_type", Type);
            writer.WriteStringValue("updated_by", UpdatedBy);
            writer.WriteStringValue("updated_by_name", UpdatedByName);
            writer.WriteStringValue("user_id", UserId);
            writer.WriteStringValue("user_name", UserName);
            writer.WriteCollectionOfPrimitiveValues<string>("users", Users);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
