// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Close.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class UpdateNoteActivity : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The activity_at property</summary>
        public DateTimeOffset? ActivityAt { get; set; }
        /// <summary>The attachments property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Close.OpenApiClient.Models.UpdateNoteActivityAttachmentsItem>? Attachments { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Close.OpenApiClient.Models.UpdateNoteActivityAttachmentsItem> Attachments { get; set; }
#endif
        /// <summary>The contact_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ContactId { get; set; }
#nullable restore
#else
        public string ContactId { get; set; }
#endif
        /// <summary>The note property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Note { get; set; }
#nullable restore
#else
        public string Note { get; set; }
#endif
        /// <summary>The note_html property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NoteHtml { get; set; }
#nullable restore
#else
        public string NoteHtml { get; set; }
#endif
        /// <summary>The pinned property</summary>
        public bool? Pinned { get; set; }
        /// <summary>The title property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Close.OpenApiClient.Models.UpdateNoteActivity"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Close.OpenApiClient.Models.UpdateNoteActivity CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Close.OpenApiClient.Models.UpdateNoteActivity();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "activity_at", n => { ActivityAt = n.GetDateTimeOffsetValue(); } },
                { "attachments", n => { Attachments = n.GetCollectionOfObjectValues<global::Soenneker.Close.OpenApiClient.Models.UpdateNoteActivityAttachmentsItem>(global::Soenneker.Close.OpenApiClient.Models.UpdateNoteActivityAttachmentsItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "contact_id", n => { ContactId = n.GetStringValue(); } },
                { "note", n => { Note = n.GetStringValue(); } },
                { "note_html", n => { NoteHtml = n.GetStringValue(); } },
                { "pinned", n => { Pinned = n.GetBoolValue(); } },
                { "title", n => { Title = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("activity_at", ActivityAt);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Close.OpenApiClient.Models.UpdateNoteActivityAttachmentsItem>("attachments", Attachments);
            writer.WriteStringValue("contact_id", ContactId);
            writer.WriteStringValue("note", Note);
            writer.WriteStringValue("note_html", NoteHtml);
            writer.WriteBoolValue("pinned", Pinned);
            writer.WriteStringValue("title", Title);
        }
    }
}
#pragma warning restore CS0618
